### ISSUE TITLE
Unarchived Project - map won't load

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#1021]
### Steps to reproduce the error
On demo.cadasta.org...

- Went to organization page for My Land Rights
- Viewed all projects
- Unarchived Mount Hood Rights Mapping
- Went to project page

### Actual behavior

The map fails to load (in Safari, Chrome and Firefox; true after reloads for all)

![image](https://cloud.githubusercontent.com/assets/3361475/21464660/d8543324-c938-11e6-98a6-0f788ad6dc31.png)

### Expected behavior

The map should load.

**Comment by dpalomino** [comment]
Hi @bethschechter! I've been taking a look and I think what it's happening here is that the zoom level is so high that we cannot see any detail but only a white page. If you zoom out a bit we can see the map details (at least with the users I've tested with). Can you please take a look and confirm if this is the case? 

I suspect that the location in that project is not shown at that zoom level because it's a polyline.

**Comment by dpalomino** [comment]
Hi @bethschechter. Were you able to check if the zoom level was the cause of the issue?

**Comment by dpalomino** [comment]
Not a real issue, just caused by the zoom level used.
