### ISSUE TITLE
Rework ellipsis menu

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1023]
After the review with @clash99 (thanks!), and based on the feedback we have about the ellipsis menu, we will rework the ellipsis menu to have another option that would be better understandable for all users.

**Comment by clash99** [comment]
For top menu next to "Add location" button (only administrators can view this menu).  Recommend still using ellipsis menu for smallest responsive screen since this segment of users is basically non-existent.

![screenshot 2016-12-27 11 08 11](https://cloud.githubusercontent.com/assets/1119621/21504507/2114fbb8-cc25-11e6-8b08-bd153f19d979.png)
![screenshot 2016-12-27 11 07 58](https://cloud.githubusercontent.com/assets/1119621/21504510/28ca6c76-cc25-11e6-98aa-2dc3306838e4.png)
![screenshot 2016-12-27 11 07 44](https://cloud.githubusercontent.com/assets/1119621/21504511/2ec0b856-cc25-11e6-8aca-3a04b73ffb02.png)

Still working on options for other areas ellipsis menu is used.

**Comment by clash99** [comment]
**For Detail pages - location, relationship, party:** (edit and delete are the only menu options)

<img width="749" alt="screenshot 2016-12-27 16 44 55" src="https://cloud.githubusercontent.com/assets/1119621/21510172/e40b303a-cc55-11e6-88af-111a41766f23.png">
<img width="749" alt="screenshot 2016-12-27 17 03 22" src="https://cloud.githubusercontent.com/assets/1119621/21510212/72b00eb4-cc56-11e6-87b0-d7934335f3e2.png">
<img width="1436" alt="screenshot 2016-12-27 16 46 29" src="https://cloud.githubusercontent.com/assets/1119621/21510190/2ec4852c-cc56-11e6-9218-7573355b1772.png">

**Comment by clash99** [comment]
Added "Location > XXXX" title to edit pages for location details and relationship details to improve context.

![screenshot 2016-12-27 17 20 13](https://cloud.githubusercontent.com/assets/1119621/21510424/c83a03f6-cc58-11e6-8db2-20564f0c3bb7.png)

![screenshot 2016-12-27 17 15 46](https://cloud.githubusercontent.com/assets/1119621/21510372/2444e84c-cc58-11e6-8dd8-b00dafbfab3b.png)

**Comment by wonderchook** [comment]
I like this, but I thought we weren't generally letting people delete things. @dpalomino what level of user would be able to delete? One of the issues is until we have full versioning we don't have a way for people to see that something was deleted.

**Comment by seav** [comment]
@wonderchook: Based on the code, we've had the record delete feature in the platform for a really long time now since at least June 2016 and this is available to project managers and data collectors, but not project users. While nothing is truly deleted because we have django-simple-history (which we will be using when we finally implement the bitemporal database), it is true that users do not have access to the deletion log or history.

**Comment by clash99** [comment]
cc: @bethschechter This changes ellipsis menu.  Another task is on the horizon that change project and organization wrapper "add" buttons too #1027.

**Comment by wonderchook** [comment]
@seav I don't think we want to put delete at the same level as edit though in the interface. I wasn't saying we didn't have the feature, my concern was making it too easy to delete.

**Comment by seav** [comment]
It will be kinda hard to deemphasize the delete function. Right now, this is hidden together with the edit function and since editing is a common action, users are seeing the delete function anyway. If we go with Chandra's proposal here with a one-click edit button but still hide the delete function behind an ellipsis menu, that menu will only contain the delete function, which makes it weird and therefore conspicuous.

I'd like to think that people using the platform would not be deleting stuff indiscriminately so I don't think showing a delete button together with the edit button is problematic. After all, OSM users who use iD can easily delete stuff too and it has not been a huge problem.

**Comment by clash99** [comment]
I know @dpalomino is out this week but some of the feedback I received from the training sessions was that users were having a hard time deleting a location.  The ellipsis menu wasn't intuitive to them.  With eliminating that menu, the current actions of edit and delete were put where you see then now.  

The delete does prompt a confirmation modal so it is a two-step process.  If it is an action we allow users to perform, then I wouldn't suggest hiding it.  If we want to put it as an action on the edit page and remove the delete button upfront, then it would be a three-step process.  My only concern here is that it doesn't repeat the delete pattern anywhere else on the platform so we would be making a new one.  Let me know if you would like to consider this option.

**Comment by wonderchook** [comment]
there was much "fear" of people accidentally deleting or possibly on purpose deleting things in the past (prior to building out the platform as it is). Perhaps this isn't the same anymore, but might be worth @dpalomino having a conversation with @nastynoel & @fhpichel prior to implementation.

**Comment by dpalomino** [comment]
Hi. As @clash99 was mentioning, we get some feedback from users finding difficult to edit or delete a location, I think the new UI proposal will make this much easier for them. 

If we want to restrict the ability of deleting a location, maybe we can make this option only available for project managers and not for data collectors. In any case, happy to chat with @nastynoel and @fhpichel about the different options.

**Comment by nastynoel** [comment]
@dpalomino I'm against making it easy for users to delete records and projects, particularly without more background on the number of users who are asking for this and what circumstances are they facing that makes it so important. e.g. would they be less likely to make mistakes if additional training is provided?

For me, this opens up a much more important issue wrt versioning/history. Because we don't have the ability to roll back accidental or nefarious user actions, there is unwarranted risk being opened up if we make deletion easy. The same goes for restricting this ability to select user profiles. e.g. If I'm a Project Manager who gets sacked by HfHI or Landesa, there would be nothing to stop me logging onto the Platform and wiping out all the data for a project. The impact would be profound.

**Comment by wonderchook** [comment]
@amplifi regarding @nastynoel's comments above. We could role back from backups if such a thing happened, right? It just wouldn't be particularly fun.

**Comment by dpalomino** [comment]
In reality, records are not really deleted (they are still in the database) but it is true that there is no way to recover this "deleted" locations/parties through the GUI until we implement the history log functionality (backlog id 46.00). 

An alternative solution could be to have "archived" records (parties or locations) in a similar way than we archive projects, so a project manager could be accessing to the archived records and unarchive them if needed. This would be easier to implement than the bitemporal database and could be a intermediate step.

**Comment by amplifi** [comment]
@wonderchook Correct; we have database backups for each environment. We'd restore whatever was deleted in that situation.
