### ISSUE TITLE
Tab key is not enabled for right drop-down menu in Organization page

### ISSUE THREAD

**Issue by manoramahp** [Cadasta/cadasta-platform#1034]
### Steps to reproduce the error

1. Go to Organizations.
2. Select an organization from the list
3. Move between the components using tab key
![selection_053](https://cloud.githubusercontent.com/assets/10743861/21739884/0765e842-d4ce-11e6-8386-16863f23a503.png)

### Actual behavior

Right drop down menu is not getting focus when move between the components using the tab key

### Expected behavior

It should get focus

**Comment by valaparthvi** [comment]
@wonderchook I think the tab key issue has been fixed, and Right drop down menu does get focused. 

However, one thing that I found a bit annoying was, when you go through the dropdown menu contents, you cannot really see the content that is highlighted because the background colour is very light. It would be easy on the eye if the background colour was a bit darker.
![screenshot from 2017-02-22 09-14-00](https://cloud.githubusercontent.com/assets/11015077/23196417/7e15c432-f8df-11e6-9fe5-1a5b6987da51.png)
This is moreover of an enhancement issue.
If you don't mind, I would like to work on it.

**Comment by manoramahp** [comment]
@valaparthvi Initially it didn't get focus. But now it has been fixed and gets focus on tab key press.

**Comment by wonderchook** [comment]
@valaparthvi we have specific branding and a look that is being aimed at with the current design. @clash99 is responsible for that sort of thing. I would suggest waiting on her opinion rather than working on that.

**Comment by manoramahp** [comment]
Since the issue mentioned in the title has already been fixed, closing the issue.

**Comment by valaparthvi** [comment]
@wonderchook  I understand the importance of a specific branding and look aimed by an organisation. @clash99  Do you think this suggested enhancement is required?
