### ISSUE TITLE
Unable to list Active/Archived projects in organizations with archived projects

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1035]
### Steps to reproduce the error

1. Go to an organization with archived and active projects
2. Try to list the active projects. No results are shown
3. Try to list the archived projects. No results are shown 
4. Try to list All projects. Then all projects are properly shown. 

Check the video here: 
http://screencast.com/t/SqCrlTLfaV8

This is happening in staging, demo and production. 

[Please try to describe the actions that led to the incorrect behaviour
in as much detail as possible.]

### Actual behavior

See above. 

### Expected behavior

Active and archived projects should be listed.

**Comment by seav** [comment]
I can't reproduce this on both Firefox and Edge in Windows.

**Comment by seav** [comment]
As mentioned by @oliverroick on Slack, this only happens when not using the English translation.

I've tracked this down to the following lines:
https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/organization/organization_dashboard.html#L32-L36
https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/core/static/js/dataTables.selectFiltering.js#L23-L38

The strings "True" and "False" are being translated but the JavaScript still filters the table on the English words.
