### ISSUE TITLE
Column sort by Last Updated not working correctly

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1041]
### Steps to reproduce the error

1. Go to projects index page from top nav (can replicate in staging and demo)
2. Select the column header for Last Updated so that it sorts ascending/ descending

### Actual behavior

Rows are not sorted according to date last updated

### Expected behavior

Rows would be sorted according to date last updated

Video here:  http://screencast.com/t/uwfM6gzDQ

**Comment by seav** [comment]
@clash99: As you may have guessed, this is because the sorting is based on string comparison ("Apr" comes before "Jun" which comes before "May"). I've fixed this by adding a numeric date (seconds since the Unix Epoch) to the date column using DataTables' [`data-sort` HTML attribute](https://datatables.net/examples/advanced_init/html5-data-attributes.html).

I've pushed a fix to the **bugfix/#1041** branch. Can you check if this works as you expect? I've modified the main project list page, the organization dashboard project list page, and the project resources list table.

**Comment by clash99** [comment]
Looks good @seav - thanks!
