### ISSUE TITLE
List with archived items doesn't filter

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1088]
### Steps to reproduce the error

1. Go the a list view (organizations, projects or organization projects). Make sure that list contains at least one item that is archived.
2. Try to filter the list using the search tool on the top of the table.

### Actual behavior

Nothing happens.

### Expected behavior

The list should be filtered according to the term entered into the search tool.

**Comment by seav** [comment]
OK. After investigating this, I discovered that the `innerHTML` extension [on this line](https://github.com/Cadasta/cadasta-platform/pull/658/commits/f98bb58a122cd2a07dde021945d35706d1e60435#diff-8c5cd5b0b486f8cb5f5f52c56abff4a2R20) is obliterating the existing event handlers on the search input form rendering it inactive (the input field is being recreated). So I will be submitting a PR shortly to make turn this into a regular DOM manipulation instead of `innerHTML`.
