### ISSUE TITLE
Importing these Files Exceptions Is Not Caught

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1113]
I believe the attached files should work, though at least getting a specific error instead of the generic platform error would be preferred.

[import-2-questionnaire.zip](https://github.com/Cadasta/cadasta-platform/files/765045/import-2-questionnaire.zip)

**Comment by dpalomino** [comment]
ummh... true. I think it is because of the geometry field: 
"POLYGON EMPTY"

That I guess is not supported. 

Platform error: 
"IndexError at /organizations/david-org/projects/imports20170210/import/
tuple index out of range"

Full log here: https://cadasta.slack.com/files/slackbot/F43L1AN67/import

@bjohare, can you please take a look?

**Comment by bjohare** [comment]
Geometry exceptions should be handled better in the ODK geom parser. The file imports correctly if valid WKT geoms are provided.

**Comment by bjohare** [comment]
Ok, so looking at this more closely, it seems that 'POLYGON EMPTY' is valid WKT. The import code tries to parse the incoming geom as WKT and throws an exception if there's a problem. Because this is a valid geometry, no exception is thrown. The geometry gets passed to the `SpatialUnit` model for saving to the DB. However, we run a `pre_save` check on the geom to reassign the coordinates if they fall outside the range +-180. There are no coordinates so the exception is thrown at this point. I think we should reject empty geometries during imports.. @wonderchook  what do you think?
