### ISSUE TITLE
Importer :: Ability to import WKB formatted coordinates

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1159]
WKB format is typically used when converting files to CSV in QGIS.  Therefore, it would be great to be able to import that format into Cadasta.

**Comment by dpalomino** [comment]
Thanks @SteadyCadence! 

In backlog: backlogid 4.11

**Comment by valaparthvi** [comment]
Are sample data and sample questionnaires available to load and test? If so, where can I find them?

**Comment by laura-barluzzi** [comment]
Hi @SteadyCadence @dpalomino, I'm looking at this bug and I was wondering if I got it right -- does this ask to just enable users to import data .WKB? Along with CSV and XLSX? Is there any other related issue? Thanks.

**Comment by SteadyCadence** [comment]
Hey @laura-barluzzi!

WKB is a geometry format.  Users would be able to import CSV and XLSX with the WKB format (instead of the WKT format, which is the only one Cadasta currently supports).  

http://gis.stackexchange.com/questions/3808/how-to-convert-wkb-to-wkt

@bjohare may have some suggestions as well.

**Comment by laura-barluzzi** [comment]
Hi @SteadyCadence , @bjohare  and @dpalomino. I wanted to share with you my idea to approach this issue so that I work on it in the next days. I think I can fix this by doing 3 jobs: 

1. Create a file `test_wkb.csv` with location_geometry in WKB format;
2. Modify the file `test_importers.py` by adding `self.test_wkb = '/organization/tests/files/test_wkb.csv'` and by creating a method  `test_import_with_wkb`;
3. Add the `wkb_geom_to_wkt` in the xform/utils.py where there is already `odk_geom_to_wkt(coords)` and call it in the `validators.py` inside the function `validate_row`.

Does this look reasonable to you?

**Comment by laura-barluzzi** [comment]
I added a unit test for importing WKB and the test actually passed. It seems that the import of WKB formats already works. You can see here my [last commit](https://github.com/laura-barluzzi/cadasta-platform/commit/c0fa249021bd9829728ce6c95db567b1f68786f9) that adds the test on the branch bugfix/#1159.

Is there anything else to do to support WKB?

**Comment by MappingKat** [comment]
@laura-barluzzi Interesting! Let me take a deeper dive tomorrow. I remember running into an issue when I tried importing a WKB geometry. And now I can't remember what the issue was exactly. 

Ill get back to you tomorrow. Thanks for your hard work and patience!

**Comment by MappingKat** [comment]
Oops used personal GitHub account. I'm @steadycadence.

**Comment by SteadyCadence** [comment]
@laura-barluzzi, you are right!  It does already support WKB.  Excellent.  I must have done something funky with some multi-polygons.  

That test will still be helpful.

**Comment by laura-barluzzi** [comment]
@MappingKat great to hear! Should I do a PR with the tests then?

**Comment by SteadyCadence** [comment]
Thanks!  The team will review when we have time!  Thank you, @laura-barluzzi!
