### ISSUE TITLE
Include a "Demo" label to make users more clear that they are in demo site

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1164]
Currently there is no way for the users to distinguish whether they are in demo or in platform site. We should include a "Demo" notice in demo.cadasta.org site to make this more clear. 

@clash99 was already working on a proposal (thanks!).

**Comment by wonderchook** [comment]
@dpalomino @clash99 what if instead we make it possible to label each system? Eventually I see us having versions running on org's own networks, we should probably have a way to tell users that too.

**Comment by clash99** [comment]
@dpalomino, @wonderchook, @aliensunrise - What are your thoughts on the quick sketches below for adding a site label around the logo. I'm not sure how much emphasis to put on it. I like the darker "platform" site label versus the lighter. Other ideas? Which best matches what you envisioned?

Option 1: 
<img width="464" alt="screenshot 2017-06-26 18 12 27" src="https://user-images.githubusercontent.com/1119621/27586655-d5d290a4-5b06-11e7-9798-22296a44fac5.png">

Option 2:
![ss-platform-1](https://user-images.githubusercontent.com/1119621/27586963-24e41b94-5b08-11e7-8b3c-eccea2fefe29.png)

Option 3:
![ss-platform-2](https://user-images.githubusercontent.com/1119621/27586964-24e4d494-5b08-11e7-8beb-c988e3285d28.png)

Option 4:
![ss-platform-3](https://user-images.githubusercontent.com/1119621/27586965-24e51166-5b08-11e7-9aed-bc5ce41035c3.png)

**Comment by clash99** [comment]
Labels needed:

- Platform
- Demo
- Staging
- Local

**Comment by wonderchook** [comment]
I think option 1 or 3 is good. Though I'm wondering if we want to provide more warning if people are on Staging or Demo. 

Regarding the list of labels needed, yes that is what we need but we should make sure we can put any label in if needed.

**Comment by clash99** [comment]
Added placeholder text and css for new site label in branch feature/#1164-sitelabel (based off feature/project-dashboard because of new header styling). 

@amplifi - We need to add conditional logic where the placeholder text is so that the resulting labels are: platform, demo, staging and local. I believe you said you could do it through ansible but let me know if you need anything else from me. Thanks!

Screenshots:

<img width="784" alt="screenshot 2017-06-27 12 08 52" src="https://user-images.githubusercontent.com/1119621/27600616-2be44804-5b32-11e7-94fe-02711ca26f37.png">
<img width="497" alt="screenshot 2017-06-27 12 08 31" src="https://user-images.githubusercontent.com/1119621/27600617-2be815e2-5b32-11e7-9d26-b574ac21dcc6.png">
<img width="1229" alt="screenshot 2017-06-27 11 57 24" src="https://user-images.githubusercontent.com/1119621/27600618-2be9df3a-5b32-11e7-97dc-16b38c8afee0.png">

**Comment by amplifi** [comment]
Thanks, @clash! I've committed the Ansible updates to the `feature/#1164-sitelabel` branch; includes the dynamic write of env identifier to the base HTML template. I did it the same way we did the Google Analytics include, but if you'd prefer any changes let me know. Tested and working for me in dev.

**Comment by dpalomino** [comment]
@clash99 @wonderchook @amplifi 

I also like options 1 or 3. 

Regarding the labels, I think we could be more explicit with "platform" meaning production platform. What about this, instead of "Platform" we use "Live" or "Production"? (I personally prefer Production): 
- Live or Production
- Demo 
- Staging
- Local

**Comment by clash99** [comment]
@dpalomino I think from a user's perspective "platform" works better. Live or production would be confusing since in most user's context it doesn't mean anything. It really only makes sense in the tech world we live in :)

**Comment by clash99** [comment]
Screenshot: <img width="800" alt="screenshot 2017-06-28 10 18 16" src="https://user-images.githubusercontent.com/1119621/27657619-e5c45346-5c12-11e7-98e4-676a473f6f02.png">
