### ISSUE TITLE
Password Reset Email Issue

### ISSUE THREAD

**Issue by dvlshah** [Cadasta/cadasta-platform#1183]
@oliverroick @wonderchook 

### Steps to reproduce the error

1)First make two different accounts on cadasta platform
2) Sign in with 1st account  
3)Go to edit profile and select option of reset password
4)Now enter email address of second account you created
5)It will accept all email addresses that are present in user database of cadasta platform (In our case second account).

### Actual behavior

Now if you enter an email address of any other user on platform(in our case the second account) it still accepts it and sends password reset email to the email address even though user with that email address has not actually asked for it.That should not be the case.
It might happen that a faulty user may keep on entering other users emails making their mailboxes flooded with password reset emails.

### Expected behavior

The password reset email field should only accept email address belonging to that particular account.So that we can stop the redundant password reset mail that other have not asked for.

**Comment by amplifi** [comment]
@dvlshah This is expected behavior, not a bug. The purpose of any password reset form is to reset an account's password when the user doesn't know the current password, thus it should accept any email address. Platform users, particularly project admins, have a need to initiate resets for other platform users.

Please refrain from tagging GitHub users in issues and PRs, unless responding directly to a comment. All issues and PRs will be addressed as soon as possible in order of urgency.

**Comment by dvlshah** [comment]
@amplifi  Thanks for input.Sorry for inconvenience caused.
