### ISSUE TITLE
Page refreshes multiple times on clicking inline manual icon

### ISSUE THREAD

**Issue by sahil865gupta** [Cadasta/cadasta-platform#1187]
On clicking inline-manual icon at the top right, the page redirects to /dashboard and refreshes multiple times. I think it should have shown some walk-through.
![screenshot from 2017-03-03 20-29-34](https://cloud.githubusercontent.com/assets/16779465/23556215/d21a395e-0051-11e7-9cc8-bfe9b116db6a.png)

**Comment by wonderchook** [comment]
@bethschechter could you take a look?

**Comment by bethschechter** [comment]
@wonderchook I think this has to do with the conditionals we're trying to use. Unfortunately I don't think they work that well. My suggestion is to remove that questionmark.

**Comment by bethschechter** [comment]
@clash99 how did you make that questionmark up by the sign-in? I'm trying to find it under the Cadasta demo org and am not seeing it

**Comment by SteadyCadence** [comment]
It looks like it was successfully removed on `platform`, but not on `demo`.

**Comment by clash99** [comment]
**Platform:**  The question mark by sign in should never be on platform since it is only to help users sign in on demo to view demo user permissions.  This appears correctly.

**Demo:**  The question mark should now only show to users that are not registered.  The topic is "Sign In as a Guest User (19928, by cadasta)"  This appears correctly now.

There is another topic named the same but with ID 26127 that doesn't appear to be used.  I'm wondering if we should remove that one to avoid confusion.  I've created another segment "Everyone except demo user".  We should create a separate topic that will walkthrough logging out and then logging in as demo user.  Ideally that question mark will only show to users not logged in as "demo user".

**Comment by dpalomino** [comment]
ok, so this now seems to be fixed. Please reopen if needed.
