### ISSUE TITLE
Error messages during organization creation are not cleared

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1220]
### Steps to reproduce the error

Attempt to create an organization with an empty name. It will show you the appropriate empty name error message. Then enter an organization name that already exists.

### Actual behavior

Both error messages appear simultaneously. (The same error occurs no matter which order you trigger them in succession.)

<img width="369" alt="screen shot 2017-03-07 at 9 05 42 pm" src="https://cloud.githubusercontent.com/assets/4269749/23660186/31cb263e-037b-11e7-92bc-4ca27e2f3b55.png">

### Expected behavior

Any visible error message should be cleared upon clicking "Save", so that only the applicable error message appears after a new error is found. Also "Name" in the "Organization with this Name already exists" error message should be lowercase.

**Comment by yoshi2095** [comment]
I am working on this bug. Thanks.

**Comment by khantaalaman** [comment]
The bug has been fixed.

Supporting GIF:

![optimised](https://cloud.githubusercontent.com/assets/18065231/23729769/d2b987ca-0489-11e7-908f-3175f5f929b6.gif)

PS: Sorry for buggy GIFs.

**Comment by oliverroick** [comment]
Just curious, is that something that happens in other forms as well? Say the project form for example? If yes, we need a generic solution that works across all forms and all fields.

**Comment by khantaalaman** [comment]
Cool @oliverroick , I will look into this and update the PR accordingly. By the way, I anyway need to update the PR for making the work "Name" lowercase. Sorry to have skipped that by mistake.

Thanks!

**Comment by dpalomino** [comment]
To be tested if that is reproducible in other forms (like for projects).

**Comment by dpalomino** [comment]
Retested in the forms for creating projects. Interestingly behaviour is slightly different: 

1. Trying to create an empty name project > proper error message shown ("This field is required")
2. Trying to use an existing name > Error message is cleared and proper message is shown ("Project with this name already exists in this organization")

However inverting the order (first use an existing name and then try to use an empty name) presents both error messages: 

![screen shot 2017-03-30 at 00 28 32](https://cloud.githubusercontent.com/assets/17198051/24479639/87194226-14e0-11e7-8df1-a26f1f653cbf.png)

I think this is a much more corner case.

**Comment by khantaalaman** [comment]
Hi @dpalomino, the PR has been updated and now takes care of error messages while creating a new project.
Perhaps, as @oliverroick mentioned about having a generic solution taking care of all forms and related fields, I believe we should add a similar logic ( as in PR ) to one of the js files instead of specific `.html` files. In case we are going for that, I was planning to add necessary piece of code in `form_submit_once.js` file. Is doing so the best choice or there can be a better way?
Also, I tried but couldn't find the file which is responsible for showing "Name" instead of "name" in the error message. It would be really grateful of someone who can point out that particular file. Once found, we will also need to make necessary changes in `test_duplicate_name_error` in `test_forms.py`.

Looking forward to completely fix this issue.

Thanks! :)

**Comment by yoshi2095** [comment]
@khantaalaman it's in cadasta/organization/tests/test_forms.py line 68. Am I right @dpalomino @oliverroick

**Comment by khantaalaman** [comment]
@yoshi2095 I have already mentioned it as the location where we would have to make the change and it's a test.

> `Once found, we will also need to make necessary changes in test_duplicate_name_error in test_forms.py

I am not getting the file responsible for the feature itself and not the test.

**Comment by oliverroick** [comment]
We're using [Parsley](http://parsleyjs.org/) to do client-side form validation. There might be a way to make Parsley use the same element to display error messages that Django does. That way you can have Parsley take care of the problem and it will be added to all forms. 

If that's not possible, you can add that functionality to `form_submit_once` but I would then rename the file to a more generic name because it handles different aspects of form submission.

**Comment by dpalomino** [comment]
@clash99 volunteered to take a look, thanks!

**Comment by clash99** [comment]
This string is translated in current format so added explicit validation message.

![screenshot 2017-04-14 13 31 27](https://cloud.githubusercontent.com/assets/1119621/25052353/0c3cfafa-2117-11e7-98d4-0b1cebf76828.png)
