### ISSUE TITLE
Critical: Emojis should not be valid Org or Project names

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1224]
### Steps to reproduce the error

**DO NOT test this in any live environment (staging, demo, or production). Test in dev VM only!!**

**This bug breaks the platform and results in data corruption.**

Create a new org, project,  whatever and give it an emoji for a name. Click Save.

### Actual behavior

Emoji is saved as the entity's name, and the platform dies in a fire trying to display it.

### Expected behavior

Don't allow emoji to be accepted by an input field on the platform. (Related but separate to #1157 )

**Comment by oliverroick** [comment]
I had a look at this and the problem was not so much the use of emojis per se but rather that the name contained only emojis. That resulted in an empty slug which broke the platform. If you have a name like "I need 🍺" everything is ok because the resulting slug is `i-need`.

We can make emoji-only names for organizations and projects work, if we use a default slug whenever slugifying a name results in an empty slug. I have a solution ready that uses the model name, so if the organization's or project's name is just "🍺🍺🍺🍺" the resulting slug would be `organization` or `project`, respectively.

![screen shot 2017-03-09 at 14 28 43](https://cloud.githubusercontent.com/assets/159510/23752263/ee99656e-04d4-11e7-82ab-7133b6411185.png)

The question is: Do we want to allow emojis at all? My take is, why not? And if yes, is the proposed solution using the model name acceptable? 

If we decide not to allow emojis the solution is more complex and will be folded together with #1157.

**Comment by amplifi** [comment]
The empty slug broke the platform, but the emoji char also caused breaks in ElasticSearch. If we're going to support emoji we'll need to make sure it's supported throughout; ES, imports, exports, ODK, etc.

**Comment by linzjax** [comment]
I've been using emoji's when testing ODK on my local-env and they translated to the platform without any complaints, but that was before we had ES.
