### ISSUE TITLE
Error when uploading questionaires with accents in the name columns

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1238]
### Steps to reproduce the error

1. Create a questionnaire in French (or a language with accents).  Use words with accents in the name (keys) column, like pièces.  
2.  Upload questionnaire to a new project
3. Get an error message like `[row : 103] Invalid question name [fournies_pièces]Names must begin with a letter, colon, or underscore.Subsequent characters can include numbers, dashes, and periods.`

### Actual behavior

You are unable to upload questionnaires with words containing accents in the name columns. 

### Expected behavior

If we want to support other languages, it would be useful to be able to upload questionnaires with names that have other languages; however, the labels do support accents, so there is a workaround (which is to just not include accents in the name columns).

**Comment by wonderchook** [comment]
Btw does this happen with other fonts as well?

**Comment by dpalomino** [comment]
This is because names need to only include letters (without accents, etc), numbers and/or underscores, and start with a letter. AFAIK this is a limitation of xforms, not ours... 

With labels this is not happening of course. 

I think we should be safe closing this issue. Please reopen if I'm missing something.
