### ISSUE TITLE
Remove confirm password fields

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1242]
With the new "show password" option, I think we can remove the second password field (confirm password).  Typically the confirm password is to enable the user to verify they correctly typed in the password in the first masked password field.   Thoughts?

**Comment by wonderchook** [comment]
Reasonable to me, who wants to enter their password twice anyway? Though we should probably fix this ticket at the same time #1236

**Comment by amplifi** [comment]
We shouldn't remove the confirm password field, because we shouldn't be encouraging users to show their password in plaintext. I'm on the fence about having unmasking as a feature to begin with, but we shouldn't make that the only way for users to verify their passwords. Having to use the forgotten password link is a negative UX, and it's only a matter of time before someone exposes their password in plaintext while screensharing, giving a live demo/on a projector, using their laptop in public where the password is viewed over their shoulder or captured on a security camera, using a shared computer with malware, etc. We should be enforcing the concept that a password is meant to be hidden and secret; unmasking encourages people to expose it.

**Comment by wonderchook** [comment]
@amplifi I was not understanding what you brought up regarding demos until checking out staging today!

Okay so I think there are couple things we should consider, here are my thoughts:
* I don't think the password unmask button should be on the login at all. Agreed on not accidentally revealing password
* I do think we should remove the password confirm box, but then we need the reveal button on all screens where people set or reset their password.

**Comment by clash99** [comment]
I agree on both points. If this is final, I can make the changes today.  Just let me know....

**Comment by wonderchook** [comment]
@dpalomino in agreement on this? I think we need to remove the unmasking on login prior to release no matter what

**Comment by dpalomino** [comment]
Hi @wonderchook @clash99 @amplifi.  Yes agree on both points as well.

**Comment by clash99** [comment]
**Rules I used to make changes:**  
- Entering your current password = no unmask option.  
- Entering a new password = mask option.
- Removed second confirm password field.

Pages with new changes:

**Login**

![screenshot 2017-03-10 11 39 13](https://cloud.githubusercontent.com/assets/1119621/23806828/d7e89d6c-0588-11e7-8941-71876c84f5a8.png)

**Register**

![screenshot 2017-03-10 11 40 18](https://cloud.githubusercontent.com/assets/1119621/23806849/eaaa042c-0588-11e7-86ce-77e873653785.png)

**Change password**

![screenshot 2017-03-10 11 53 30](https://cloud.githubusercontent.com/assets/1119621/23806877/039ea56e-0589-11e7-81c0-447a97264d7a.png)

**Reset password**

![screenshot 2017-03-10 11 54 48](https://cloud.githubusercontent.com/assets/1119621/23806894/119f4650-0589-11e7-8871-6a8a60128e8c.png)

**Comment by clash99** [comment]
I've submitted a PR to remove mask option from current password fields on login and change password fields since that is needed for this sprint.  Removing the confirm password field is going to take more time.

**Comment by amplifi** [comment]
@wonderchook 👍 Agreed on both points, too. @clash The mocks look good to me!

**Comment by dpalomino** [comment]
Hi @clash99, also looks good to me!
