### ISSUE TITLE
SMAP: Implement frontend toolchain

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#1244]
Part of the Map Single Page App epic (#1031)

# Task

SMAP adds a lot of additional javascript. We currently have no process for compressing and uglifying JS resources. We should modernize our frontend toolchain to take advantage of developments in this area.. see http://owaislone.org/blog/modern-frontends-with-django/

**Comment by linzjax** [comment]
So based on the bit of research I've done it seems like our two best options are [grunt](https://gruntjs.com/) or [gulp](http://gulpjs.com/). Webpack and the like might be better in the future because it requires fewer dependencies, but it also requires a _whole_ lot more setup.

Although Gulp seems to be (slightly) faster and more flexible, given that we are a django forward group, I would recommend Grunt based on syntax since it's closer to what people would already be used to (i.e. it doesn't involve having to learn about piping and streams).

So Grunt would be my recommendation. If anyone objects or has opinions, please feel free to chime in. If that works, I'll take a look at how best to [implement it](https://lincolnloop.com/blog/simplifying-your-django-frontend-tasks-grunt/)

**Comment by wonderchook** [comment]
@linzjax this still needs to be done?

**Comment by linzjax** [comment]
Yeah. It's going to take a bit of thinking about how we currently structure our js files. I also don't know what priority it's at.

**Comment by linzjax** [comment]
### Current JS Ecosystem (minus `edit` file added in smap)

### dataTables

`dataTables.conditionalPaging.js`: hides page buttons if page total <= 1

- Used everywhere there are dataTables

`dataTables.forms.js`: for when a form contains dataTable fields as inputs

- Resource forms

`dataTables.hooks.js`: Adds the search box and custom language. Required for all dataTables

- Used everywhere there are dataTables

`dataTables.selectFiltering.js`: only used on tables with archive (and search?)

- Project List
- Organization Lists
- Organization Detail Page

### SMap

`catiline.js`: external library. Allows for webworkers to pass around functions and variables.

`index.js`: Initializes map, router, hash, and adds event listeners

`L.Hash.js`: external library. Adds hash to the end of the coordinates

`L.TileLayer.GeoJSON.js`: external library. Uses vector tiling to load map and GeoJSON layer

`lazytiles.js`: checks if a tile or its parent has already been loaded

`map.js`: calls L.TileLayer.GeoJSON, adds the layers, loads the project extent, renders spatial resources, initializes geolocate and other map controls.

`router.js`: formats urls for async calls and finds appropriate router path for each hash. Makes an AJAX call to the async url, handles error responses, or formats response

`router_mixins.js`: handles all of the logic for each individual route. Is it display or modal, is there a form, are there event hooks that need to be added, should the state be updated, etc?

- Could probably be broken down into smaller, more manageable files?

`routes.js`: creates a dictionary that defines each individual page's "route" based on the url hash. Calls two functions: updatePage and updateState.

### Leaflet

`L.Map.Deflate.js`: external library. at certain zoom levels, turns polygons into points

- Currently only used on dashboard

`Leaflet.Editable.js`: external library. Used for geometry manipulation

- Did we switch libraries?

`leaflet.groupedlayercontrol.min.js`: external library. groups overlays together.

- Used on all pages with a leaflet map

`leaflet.markercluster.js`: external library. At certain zoom levels, clusters geometries together into circles with total geometry count displayed

- Currently only used on dashboard

`map_utils.js`: NO LONGER USED

### Organization Specific

`contacts.js`: used to create the contact list in an Organization.

### Forms

`file-upload.js`: used anytime a form has a "file upload" options (questionnaires, resources)

- Project creation
- Resources

`form_submit_once.js`: After save/submit has been clicked, the button is disabled which the form is processed

- All forms

`parsley.js`: external library. Used for automatic for field validation

- All forms

`parsleyAddValidator.js`: validates passwords

- Login
- Registration
- Edit Account

`parsleyConfig.js`: configure parsley for bootsrap 3 forms

- All forms

`party_attr.js`: used to hide or display party attribute questions in add/edit party forms based on party_type

- Relationship Add form

`password_widget.js`: adds an eye to allow users to view their password (rather than dots)

- Login
- Registration
- Edit Account

`rel_new_item.js`: if adding a new party (rather than one selected from the list), turns `#new_entity_field` on and shows form fields

- Relationship Add form

`rel_spatial.js`: NOT USED?

`rel_tenure.js`: Add party button trigger - removes select-list and replaces space with party form. Select-list trigger: when clicking on a specific party, autofills necessary input fields

- Relationship Add Form

`rel_type.js`: NOT USED?

`script_add_lib.js`: calls function from `dataTables.forms.js` and adds event handles that allows user to click on a dataTable row and have the checkbox be clicked.

- Resource forms

`xlang.js`: used to toggle language tables displayed in project questionnaire

- Project Pages

### Other

`inline-manual-player.js`: (shocking) for the inline manual player

### Min files

`bootstrap.min.js`

`jquery-ui.min.js`

`leaflet.groupedlayercontrol.min.js`

**Comment by clash99** [comment]
You may want to look at #1416. I removed bootstrap and jquery is files since they are pulled in with datatables cdn link.

**Comment by oliverroick** [comment]
@linzjax: Where you thinking of folding the JS of all pages into one file or just the ones used in SMAP? I would focus on SMAP only, otherwise, it will be difficult to get right.

**Comment by linzjax** [comment]
@oliverroick I was planning on starting with just the SMAP stuff, and then seeing if there were other things we could wrap together (but I'm not sure how feasible that is).
