### ISSUE TITLE
Add thumbnail preview to edit resources page

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1264]
Currently there isn't a thumbnail preview on the edit resources page.  Ideally we could use the same 128 X 128 on the resource detail page and add it to the resource edit page.

**Current page:**

![screenshot 2017-03-09 16 56 17](https://cloud.githubusercontent.com/assets/1119621/23774470/6406f032-04e9-11e7-8b6a-a03f791216d2.png)

**Proposed change:**

![edit preview](https://cloud.githubusercontent.com/assets/1119621/23774403/1bd003a8-04e9-11e7-8b4a-d774485d23fd.png)

**Comment by clash99** [comment]
@dpalomino Marking as first contribution friendly.  Feel free to remove if you disagree.

**Comment by khantaalaman** [comment]
A PR has been submitted for this issue. Please suggest further improvement.

Supporting screenshot:

![screenshot from 2017-03-10 04-50-49](https://cloud.githubusercontent.com/assets/18065231/23775203/79efa25e-054d-11e7-8cfc-8cd1dbba9e28.png)


Thanks!

**Comment by yoshi2095** [comment]
Hi, @clash99 @dpalomino I was going through the bug Cadasta/cadasta-platform#1264. I was wondering what exactly happens in the background when I click the (Remove) link. I mean, I was searching through the code base to find this link because it links through the `{{form.file}}` tag in the resources/form.html template, but couldn't find it. All I want to figure out is, after clicking on this link, I need to know the object which gets a "none" value, because @clash99 suggested to include something like `{% if form.original_file.value == none %}` in the template to determine if the "thumbnail" or "browse file option" should show, which will eliminate the need to add JavaScript. So, does clicking on this link actually changes some variable's value to "none"?
If yes, then when I refresh the page after clicking this remove link, why does the name of the same image appear again?
According to me, it should not appear as the image has been removed and some variable's value has been converted to none in the backend. But I think this is not happening. Please correct me if I am misleading somewhere. Thanks.

**Comment by clash99** [comment]
@yoshi2095 and @khantaalaman - So the current solution doesn't work because the form is reused on things like adding new resources so as-is, it is broken when uploading a new resource.  See screenshot below.  The file upload is mostly contained in file-upload.js.  I hope that helps.  Let me know if you have any questions.

<img width="924" alt="screenshot 2017-04-04 16 55 29" src="https://cloud.githubusercontent.com/assets/1119621/24680862/36fdafee-1958-11e7-8d3f-db34f55332ba.png">

**Comment by laura-barluzzi** [comment]
@clash99 I could probably address this very easily if we clarify our mind on how we want it to work. I could simply display it as in the previous page "Resource detail" and, in case remove is clicked, the preview disappear. If a new resource is uploaded, we can show the preview as in the "Edit page" with the avatar or with can make it even simpler and not show the preview (as when you normally upload a resource). Let me know!

**Comment by clash99** [comment]
@laura-barluzzi - Sounds good. I agree with what you suggest.

**Comment by laura-barluzzi** [comment]
@clash99 ok, I first try the option A: show the preview as in "Resource detail" and then, if the user clicks on "Remove", the preview disappear (behaving as "Add resource" page, without preview). I think this is first good step.

**Comment by clash99** [comment]
<img width="1337" alt="screenshot 2017-10-04 16 18 16" src="https://user-images.githubusercontent.com/1119621/31200220-b65e68e4-a91f-11e7-9867-d3eacc98f740.png">

This is done - closing.
