### ISSUE TITLE
AssertionError at /api/v1/users/<user-name>/

### ISSUE THREAD

**Issue by rishabhiitbhu** [Cadasta/cadasta-platform#1284]
### Steps to reproduce the error
- Login with superuser (ex: 'iross' on local development server)
- visit /api/v1/users/**user-name**/

### Actual behavior

- AssertionError : 
>Expected view UserAdminDetail to be called with a URL keyword argument named "username". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.

### Expected behavior

According to Docs [link](https://devwiki.corp.cadasta.org/User%20management%20API#get-a-single-user) superuser should be able to see specific user's details (ex: first_name, last_name, email ) and should be able to update them.

**Comment by rishabhiitbhu** [comment]
I would like to take up this issue.
Approach:
- /vagrant/cadasta/organization/urls/api/users.py URL conf needs to be fixed. 
- URL keyword needs to named "username".

**Comment by wonderchook** [comment]
@dpalomino thoughts on this? The super users do have bugs but since I think I'm the only one that really uses that feature, it hasn't been that big a deal.

**Comment by dpalomino** [comment]
Thanks @rishabhiitbhu for raising the issue and for your collaboration. As @wonderchook was mentioning, there are some super user issues that we are not currently targeting because has very low impact. 

I'd suggest to take a look at some of [the issues](https://github.com/Cadasta/cadasta-platform/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22first%20contribution%20friendly%22) that are tagged with "First Contribution Friendly". 

You can also find more info here: 
https://github.com/Cadasta/cadasta-project-ideas/wiki/GSoC-Outreachy-Issue-Contribution-Process

Thanks!

**Comment by rishabhiitbhu** [comment]
@dpalomino thanks for your suggestion.

**Comment by oliverroick** [comment]
This issue in itself is valid and should be fixed at some point. Re-opening this.

**Comment by rishabhiitbhu** [comment]
@oliverroick we need to rename the URL keyword 'slug' to 'username' in https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/organization/urls/api/users.py this will solve this issue. I can create a PR to fix this if you say so.

**Comment by oliverroick** [comment]
I don't mind if you pick this up. Bear in mind, though, that this is a lower priority issue so it might take a while till we review and merge the PR.

**Comment by rishabhiitbhu** [comment]
@oliverroick I'm fine with that. :)
