### ISSUE TITLE
Change Password: User gets password updated even if new password is same as old password.

### ISSUE THREAD

**Issue by rishabhiitbhu** [Cadasta/cadasta-platform#1286]
### Steps to reproduce the error

- Create a User.
- Update password with new password exactly same as old password.

### Actual behavior

- Password gets updated.

### Expected behavior

- Form validation error should be raised i.e., User should be shown a Flash message saying "Password must differ from old password."

**Comment by rishabhiitbhu** [comment]
I would like to take up this issue.

Approach:

- Every Change password form submission passes through `ChangePasswordMixin` of `/cadasta/accounts/forms.py` once the user enters old password (correct) same as new password we can get them compared (extracting them from self.cleaned_data) and raise form.ValidationError with message "Password must differ from old password." 
- Add test cases to test the new changes.

**Comment by wonderchook** [comment]
@rishabhiitbhu is your intention to only check to make sure it isn't the same as the last password? 

@amplifi should we be implementing a greater password history than this?

**Comment by rishabhiitbhu** [comment]
@wonderchook yes, currently my intention is to make sure it isn't the same as the last password. I think implementing a greater password history would be great.

**Comment by amplifi** [comment]
@rishabhiitbhu Our current password policy doesn't require uniqueness against previous passwords. This is by design, so this issue is not a bug. It's not advised to implement both length/complexity requirements and password history (the same goes for forced password changes). This tends to result in less security as well as a poorer UX. Users often follow predictable patterns when changing their passwords, which makes it significantly easier & faster to crack when storing both current and previous passwords in the database (even when salted and hashed). I would recommend focusing on another issue, particularly those labeled "First Contribution Friendly."
