### ISSUE TITLE
A resource with the filename "resources.xlsx" cannot be exported correctly

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1302]
### Steps to reproduce the error
1. Add a resource named "resources.xlsx" to a project
2. Export the resources of that project.

### Actual behavior
The zip file contains a different resources.xlsx file, which contains data for the resources.

### Expected behavior
The zip file contains the original resource file intact.

**Comment by dpalomino** [comment]
Hi @seav. Is this a dup of #1303? Ta!

**Comment by ViktoriaErokhina** [comment]
Hi!

My name is Viktoria and I would like to fix this bug as part of my application to Outreachy project.

The idea I have is the following: to make an increment stamp. There are severals ways how to do that. The easiest one is just to create a dictionary <Filename, Count>. In case we care a lot about memory it's also possible to do with dictionary, but instead of having filename, we could use it's hash.
