### ISSUE TITLE
Resources with the same filename cannot be exported correctly

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1303]
### Steps to reproduce the error
1. Add a resource to a project.
2. Add a different resource with the same filename to that project.
3. Export the resources of that project.

### Actual behavior
Extracting the zip file will only produce one of the 2 resources.

### Expected behavior
Extracting the zip file will produce both resources intact.

**Comment by Sanny26** [comment]
Can I try to solve this issue? Can we append last_updated time at the end of the filename to avoid this?

**Comment by dpalomino** [comment]
Hi @Sanny26, thanks! Unless @seav thinks otherwise, I think that is a good idea. I like the proposal of adding the timestamp to the filename, but I'd restrict this only in the case of having another resource with the same file name (i.e. not appending this by default). Other alternative would be appending and incremental number (_2, _3, etc).

**Comment by ViktoriaErokhina** [comment]
Hi!

My name is Viktoria and I would like to fix this bug as part of my application to Outreachy project.

The idea I have is the following: to make an increment stamp. There are severals ways how to do that. The easiest one is just to create a dictionary <Filename, Count>. In case we care a lot about memory it's also possible to do with dictionary, but instead of having filename, we could use it's hash value.

**Comment by Sanny26** [comment]
@dpalomino Can I open a PR or should I wait ?

**Comment by dpalomino** [comment]
hi @Sanny26. Sure, feel free to open a PR. Thanks for your cooperation!

**Comment by aadityasg** [comment]
Hi @dpalomino, I have created a PR for this which uses the approach of appending an incremental counter at the end of filename (only for those which are having duplicate names). Please review the PR.
