### ISSUE TITLE
Clean-up Tasks - Ian

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#132]
- [x] Test Coverage to 100%
- [x] Test refactoring: declarative framework to reduce cut & paste
- [x] Translation sources to Transifex; add languages to Transifex
- [x] Automate SASS compilation
- [x] Functional test creation checklist

**Comment by ian-ross** [comment]
The test refactoring I did didn't quite reach the heady heights of a "declarative framework".  I did some tidying and folding of cut & paste code into utility methods, but I might have another go at this in a later sprint, because I still think there's quite a lot that could be done to make it nicer.

**Comment by ian-ross** [comment]
Decided to move view factoring task to another time.  I did enough refactoring on the test stuff to last me a while...
