### ISSUE TITLE
Archived resources are also shown in search results.

### ISSUE THREAD

**Issue by khantaalaman** [Cadasta/cadasta-platform#1354]
### Steps to reproduce the error

1. Create a resource and archive it.
2. Use search to find the resource.
3. Clicking on the resource from the search results will give DoesNotExist exception.

### Actual behavior

Archived resources appear in search results.

### Expected behavior

Archived resources should not appear in project search results.

**Comment by wonderchook** [comment]
@clash99 I'm inclined to say we shouldn't show the archived ones by default but there should be a way to select that you want to see them.

**Comment by seav** [comment]
@wonderchook: For all intents and purposes, archived resources are considered deleted in the eyes of platform users (we actually use the term "delete" instead of "archive"), and only superusers are able to view archived resources and potentially unarchive them. So for the search feature, I think there should be no option to be able to see archived resources. (Superusers have access to the database so they do not need to rely on the search feature.)

Ideally, archived resources should no longer be indexed in Elasticsearch, but since they are included (our ES indexes basically mirror our database—makes our infrastructure simpler), I plan to add an `archived=False` filter to the ES query to resolve this bug.

**Comment by wonderchook** [comment]
@seav I think that makes sense!

**Comment by dpalomino** [comment]
@amplifi, can you please take a look and let us know if that sounds good for you? ta!

**Comment by amplifi** [comment]
@dpalomino Yes, ES queries should include a filter to exclude data that is archived.

However, it is incorrect that archived data should be excluded at the ES level. We want ES to be consistent with the database, so that search results provided to the users are as accurate as possible. Because multiple users could be archiving resources, and superusers should be able to see archived resources, maintaining two inconsistent datasets (one in ES, one in the database) will result in some regular users seeing archived resources and superusers seeing only archived resources.

We should never be implementing features on the assumption that superusers will be able to access the database directly; this is extremely poor practice and only the case now as a workaround for the fact that superuser tools have not yet been developed. I can't emphasize this strongly enough: **Manual access to live production databases is bad and we should continue to avoid it as much as possible. This should never, ever be relied upon as a means of accessing project data.**

**Comment by khantaalaman** [comment]
HI @amplifi, 
I went through parts of Elasticsearch doc last evening and found [this portion](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html) of the doc to be relevant in order to achieve desired results.
It would be really great if you could tell whether I am heading in the right direction to find the correct solution.
Thanks!

**Comment by amplifi** [comment]
@khantaalaman That's the correct documentation; we should add a filter to our ElasticSearch query to exclude archived resources.

**Comment by dpalomino** [comment]
@amplifi Comment from triage: Archived resources shouldn't be indexed. Can you please take a look Adrienne?

**Comment by amplifi** [comment]
@dpalomino Please see my comment above; I've already addressed the idea that archived resources shouldn't be indexed and it is incorrect: https://github.com/Cadasta/cadasta-platform/issues/1354#issuecomment-290622487

We should not be maintaining two inconsistent data sets, and we should never be implementing features based on the assumption that super users will be manually accessing and manipulating live production databases -- this is very bad practice. We should be adding a filter on the platform side to exclude results that are archived.
