### ISSUE TITLE
Public Users can still view `records/locations` and `records/parties`

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1384]
### Steps to reproduce the error
Add a user to an organization and assign them as a Public User for a project.
Login as that user and go to that project page.
Add `/records/locations/` to the URL.
::or::
Add `/records/parties/` to the URL

### Actual behavior
They see a stripped down version of the "map" page.
They see a list of party names and types.
They don't have access to any details.

### Expected behavior
I don't think `/records/location/` is much of an issue because it's not showing you any information that you don't already have access to. But the party table should be stripped the same way that the resource table is.

**Comment by oliverroick** [comment]
This is expected behaviour; there's a discussion about this in [#961](https://github.com/Cadasta/cadasta-platform/issues/961#issuecomment-273828884). 

The behaviour is the way it is because we wanted to make listing parties consistent with listing location (or rather putting them on the map). We said you could see locations on the map, but you can't access location details if you're a public user. For parties it's the same, you know they are there but can't access them. 

I do agree though that this is confusing. Why do we show people things if you can't access them? I think this should be a binary decision, you can either see it or you can't. But refering back to yesterday's discussion in Slack the decision is not that easy as I'd like to think.

**Comment by linzjax** [comment]
Ah fair enough. It just felt like I had found "secret" pages since there wasn't a way to navigate to these pages in through the UI, but if this has all been discussed before I will go ahead and close this.
