### ISSUE TITLE
URL validation seems off

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1459]
### Steps to reproduce the error

When creating a new organization, enter an invalid url such as **as.df** in organization url field.

### Actual behavior

Seems to accept any string with a period in it (doesn't accept **asdf** but does accept **as.df**)

### Expected behavior

I would expect to get an error and that it wouldn't accept **as.df** as a url.

**Comment by seav** [comment]
*as.df* is accepted by Django because it looks like a valid domain name. (Although .df is not currently an assigned CCTLD.)

**Comment by amplifi** [comment]
Agreed; this is expected behavior and default for Django. URL validation checks that the string is formatted correctly, not that the URL entered corresponds to an existing domain/page. It would be unwieldy to continuously ensure that organization URLs are valid sites. For examples and definitions, see: https://mathiasbynens.be/demo/url-regex
