### ISSUE TITLE
Ability for photos to be viewed on the web and not downloaded

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1502]
Can we set the photos so that they can be viewed in the browser?  That would provide a lot more opportunity for me to set up dashboards and various other tools for partners to use... 

For example, if you inspect element on a resource and then right-click to "open in new tab" it will download the project instead of open it in a new tab.

**Comment by amplifi** [comment]
This is because resources get uploaded with a content-type of binary/octet-stream. Setting the type to reflect the actual file contents will default to handling based on each user's browser default; in most cases, that will be displaying the image in a browser tab. #692 is related, and these will be fixed with the async i/o in #1400
