### ISSUE TITLE
Missing js files generate 404 error

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1539]
The datepicker js files are no longer available at the CDN address hardcoded into several of the platform pages. Example broken link: 
https://cdn.rawgit.com/jquery/jquery-ui/1.12.1/ui/i18n/datepicker-en.js

<img width="1440" alt="screen shot 2017-05-25 at 5 40 11 pm" src="https://cloud.githubusercontent.com/assets/4269749/26461990/58d8507a-417f-11e7-8bcf-154f99e1e147.png">

Files affected:
[https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/party/party_add.html](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/party/party_add.html)

[https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/party/party_edit.html](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/party/party_edit.html)

[https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/party/relationship_edit.html](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/party/relationship_edit.html)

[https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/spatial/location_add.html](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/spatial/location_add.html)

[https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/spatial/location_edit.html](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/spatial/location_edit.html)

[https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/spatial/relationship_add.html](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/spatial/relationship_add.html)

**Comment by clash99** [comment]
This appears to only be the english version (-en).js. It works for all the other languages currently available on the platform such as https://cdn.rawgit.com/jquery/jquery-ui/1.12.1/ui/i18n/datepicker-fr.js.

This is because straight up -en is not available. Localization files available for the datepicker are here: https://github.com/jquery/jquery-ui/tree/master/ui/i18n. I think we want to use -en-GB. This begs the question of whether we want to move these locally so we can control the naming (which would involve maintenance when we added a new language) or create a one-off match for just this localization (with the possibility of more in the future).

@seav I think you worked on the date picker initially. What are your thoughts?

**Comment by seav** [comment]
The en (or en-US) localization file does not exist because this is the default locale of the datepicker widget. When you import a localization file, only then does the locale change. If you look at our templates, we use the following logic:

```
{% if get_current_language != "en-us" %}
{% get_current_language as LANGUAGE_CODE %}
<script src="https://cdn.rawgit.com/jquery/jquery-ui/1.12.1/ui/i18n/datepicker-{{ LANGUAGE_CODE }}.js"></script>
{% endif %}
```

I can't remember why I wrote this logic. I think `en-us` should have been just plain `en` because that is what is included in our language selection menu.

As for bringing the localization files locally, I have no strong opinion either way. Both options have their pros and cons.

**Comment by dpalomino** [comment]
@clash99, can you please take a look?

**Comment by clash99** [comment]
Closing - already merged.
