### ISSUE TITLE
Cannot files questionnaire in IE (WIP)

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1548]
### Steps to reproduce the error

1. Open IE browser (version ----) and go through "Create project" steps
2. When get to questionnaire upload, the box is greyed out for viewing the file. Can click the "Browse" button and upload file but file does not seem to upload.
3. Click "Save" and it loads the default questionnaire.

** Not sure if this is a bug from before or if it is new. 

### Actual behavior

File does not get uploaded even though it seems as if it does.

### Expected behavior

I expect the file to upload and when I click "Save" I expect to see the questions on the project.

**Comment by wonderchook** [comment]
@SteadyCadence what version of IE? I am not able to reproduce

**Comment by SteadyCadence** [comment]
I have to get that tomorrow.  Which version are you on?  The latest?  If so, I can try to have them update tomorrow.

**Comment by wonderchook** [comment]
I tried it both using Edge and IE 11

**Comment by dpalomino** [comment]
@SteadyCadence, are you getting some error message? "File type not allowed" for instance?

**Comment by dpalomino** [comment]
I tried to test with Browser Stack but I'm getting some confusing results: 

- MacOS Sierra Firefox 53: OK (I need to download a demo questionnaire first into their local machine and then upload it again, but was accepted without any issue)
- Windows 10 Edge version 15: Fail (I get the error message "File type not allowed") 
- Windows 10 IE version 11: Fail (I get the error message "File type not allowed") 
- Windows 10 FF version 53: Fail (I get the error message "File type not allowed") 
- Windows 10 FF version 58: Fail (I get the error message "File type not allowed") 
- Windows 8.1 IE version 11: Fail (I get the error message "File type not allowed") 

So I suspect this has something to do with the Browserstack environment because it's failing only with Windows machines with both IE and other browsers.

**Comment by SteadyCadence** [comment]
Ill get the version this morning and take some GIFs.  It looks like the files is uploaded but then it just doesnt work.  There are no errors.

**Comment by SteadyCadence** [comment]
Version 58.0.3029.110 (64-bit)

I think its IE 10... not sure.

**Comment by amplifi** [comment]
Version 58.0.3029.110 (64-bit) is Chrome

**Comment by SteadyCadence** [comment]
Microsoft Edge 38.14393.0.0

This is what the browser file section looks like: 
![ie](https://cloud.githubusercontent.com/assets/25337622/26668718/31a77d04-46d5-11e7-9830-97d32aaf9a8e.PNG)

**Comment by SteadyCadence** [comment]
The file uploads seem to be working today.  I wonder if it was slow internet. Though when you uploaded a file it did not show the path (now it does).  It would let you select and then the path field would be empty. 

Might have been user error...
