### ISSUE TITLE
Resources :: "Detach" button only activated for resources not attached

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1555]
### Steps to reproduce the error

Attach resource via a location and in general.
Observe that you can only "detach" ones that are not associated with anything... 

<img width="1158" alt="screen shot 2017-06-02 at 3 22 06 pm" src="https://cloud.githubusercontent.com/assets/25337622/26717385/69146752-47a7-11e7-8ae2-4d4148ddd1d4.png">

### Expected behavior
I expect the opposite.

**Comment by seav** [comment]
I assume that this screenshot is from the Resources tab? If so, then this is expected behavior. The Resources tab lists all resources in the project and also allows you to detach resources that are attached to the project itself. The first three resources are not attached to the project itself but to other entities. That's why there is no "Detach" button. On the other hand, the last resource is attached to the project itself (hence why there is a "Detach" button) but it is not attached to any other entity (hence the "0 other" note).

**Comment by clash99** [comment]
When you are looking at the detail page for that resource, you can detach it from anything it is connected to.

There was/is? a task in the backlog to add a dropdown filter to the resources index that would allow you to filter by: Attached to Project (default), Location, Relationship, Party, All. Would that help clarify the resource connections or does that make it more confusing?

**Comment by dpalomino** [comment]
Hi @clash99. Yes, there is [a task](https://github.com/Cadasta/cadasta-platform/issues/1596) for filtering resources in the backlog (although it is a low priority one). 

I think we are good to close this issue.
