### ISSUE TITLE
String Sanitation - Password reset

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1558]
Thanks @linzjax for detecting this. Issuing individual issues from the comments in PR #1395. 

Steps To Reproduce: 
1. Go to password reset process
2. I can reset my password to contain an emoji

**Comment by amp529** [comment]
This is expected behavior and a good thing.

Passwords are encrypted when stored in the database, and they aren't accessed by any other component of the platform aside from Django's auth module. So as long as the characters are Unicode (which emoji are), it's totally fine. Restricting emoji would actually restrict the overall range of possible characters in a password, and make the passwords relatively less secure.

**Comment by amplifi** [comment]
This is expected behavior and a good thing.

Passwords are encrypted when stored in the database, and they aren't accessed by any other component of the platform aside from Django's auth module. So as long as the characters are Unicode (which emoji are), it's totally fine. Restricting emoji would actually restrict the overall range of possible characters in a password, and make the passwords relatively less secure.
