### ISSUE TITLE
Date formating

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#157]
Change dates in data tables in platform to be in yyyy-mm-dd time format.

**Comment by ian-ross** [comment]
Are you sure we want to do this?  At the moment, dates are localised according to language: if you pick "French" from the language menu at the bottom right, you'll see that dates are formatted according to French usage.  Same for other languages.  I know that we try to use ISO 8601 internally for dates, but we should probably talk about what degree of localisation we want in the UI for this sort of thing and for other internationalisation questions.  (I've not worked on an application before that's gone for full internationalisation from the start, so it's not obvious to me what the best approach is.)

**Comment by wonderchook** [comment]
I think if there is a standard date by language we should use that. Though in English for example there isn't a standard, so then the yyyy-mm-dd makes sense.

**Comment by ian-ross** [comment]
We could do with having a broader discussion about internationalisation issues generally.  We're translating messages, but that's only part of full internationalisation: the other part is localisation of dates, currencies (I'm sure we'll end up with currency data in some projects), number formatting (in France and Germany, you write 1.000,00 instead of 1,000.00, for instance), and so on.  That needs to be done both for display and input (Django handles both if you let it).  I have no idea how far you want to go with that, but we ought to come up with some general guidelines.

**Comment by wonderchook** [comment]
@ian-ross yes agreed about a broader discussion. I think the formatting for data should probably be a feature itself. I can imagine eventually people could write their own formatting, but to start we would have some standard ones.

**Comment by seav** [comment]
I'd just like to comment that in my functional tests, I currently have the following code used for checking that the last login time of a user is displayed correctly. This is just an initial solution based on the format that is actually used until we have a more organized way of specifying time and date formats. 

> `formats.date_format(expected_time, "DATETIME_FORMAT")`

**Comment by wonderchook** [comment]
pushing improving this to the next release which will include broader general localization guidelines

**Comment by wonderchook** [comment]
closing in favor of fixing date formatting errors first
