### ISSUE TITLE
Geometries/location attributes not loading in one project

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1572]
### Steps to reproduce the error

1. I have only seen this behaviour with [this project](https://platform.cadasta.org/organizations/landesa/projects/odisha-data-collection/)
2. Go to that project Overview page (8 locations)
3. See "Loading locations" message for ever

Other projects are working fine.

Log from the error [here](https://cadasta.slack.com/files/slackbot/F5R9JBFBL/spatial).

**Comment by SteadyCadence** [comment]
There's a 500 error occurring on the spatial endpoint. I feel like its something in the attributes... needs investigation

**Comment by amplifi** [comment]
If you look at the stacktrace for this error, you'll see one of the locations on this project has a blank `location_type`: https://opbeat.com/cadasta/platform-prod/errors/50/

We need to either disallow adding locations with a blank type, or allow locations to load successfully despite having a blank `location_type`.

**Comment by dpalomino** [comment]
Thanks @amplifi for the analysis. I'd say it will be more flexible to allow locations without `location_type`, and cannot think in a reason for not allowing blank location_types. What do you think @SteadyCadence?

**Comment by oliverroick** [comment]
There's only one location that is affected by this record across all of our instances. It's not possible to create a location without providing the type, so it's hard the reproduce the root cause of this error (i.e., why does this one location not have a `type`). 

The project is archived, so I'm assuming it's not being used. I updated the record, so `type` is set to `PA`, and the project will at least load. 

I'm closing the ticket; we can reopen if this issue resurfaces.
