### ISSUE TITLE
Ability to add parties without relationships

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1581]
Updating description with new requirement format: 

### Problem Statement 

There is a need from some partners to be able to add parties without having to associate (yet) those parties to specific locations via a relationship entity. 

### Context / Use Case

The best example of this could be when an organization is collecting in a first phase all the information regarding the landowner, and in a second phase when going to the field an visiting the actual parcels, the information regarding the location. 

### User Story 

As a data collector, I want to be able to add a party entity using the web UI without creating first any location. 

### Description 

For doing that we will be including a "+Add party" button in the drop down Add menu, right between "+Add location" and "Add resource": 
![screen shot 2017-06-12 at 17 35 04](https://user-images.githubusercontent.com/17198051/27041862-8e0ad442-4f95-11e7-812f-9815ad86896d.png)

Clicking on "Add party" should redirect the user to the "Parties" section where a web form would be appearing on the right side to create the new party. 

Conditional attributes for party types ("IN", "GR" and "CO") should be considered in the same way as we do when adding a relationship with a new party via the "Add location" section. 

---

cc: @clash99 

We have detected a need from some partners to add a party entity without having to attach the party entity to a location via a relationship entity. That's because for instance they are collecting party information first. 

So we need a mechanism to add parties via the WUI with no relationships with locations. 

For doing that we will be including a "+Add party" button in the drop down Add menu, right between "+Add location" and "Add resource": 
![screen shot 2017-06-12 at 17 35 04](https://user-images.githubusercontent.com/17198051/27041862-8e0ad442-4f95-11e7-812f-9815ad86896d.png)

Clicking on "Add party" should redirect the user to the "Parties" section where a web form would be appearing on the right side to create the new party. 

Conditional attributes for party types "IN", "GR" and "CO" should be considered in the way as we are doing when adding a relationship with a new party via the "Add location" section.

**Comment by dpalomino** [comment]
### Problem Statement 

There is a need from some partners to be able to add parties without having to associate (yet) those parties to specific locations via a relationship entity. 

### Context / Use Case

The best example of this could be when an organization is collecting in a first phase all the information regarding the landowner, and in a second phase when going to the field an visiting the actual parcels, the information regarding the location. 

### User Story 

As a data collector, I want to be able to add a party entity using the web UI without creating first any location. 

### Description 

For doing that we will be including a "+Add party" button in the drop down Add menu, right between "+Add location" and "Add resource": 
![screen shot 2017-06-12 at 17 35 04](https://user-images.githubusercontent.com/17198051/27041862-8e0ad442-4f95-11e7-812f-9815ad86896d.png)

Clicking on "Add party" should redirect the user to the "Parties" section where a web form would be appearing on the right side to create the new party. 

Conditional attributes for party types ("IN", "GR" and "CO") should be considered in the same way as we do when adding a relationship with a new party via the "Add location" section.

**Comment by clash99** [comment]
We should also add and "add" button to the party index page.

**Comment by clash99** [comment]
## Wireframes

- [Link to wireframe document (pdf)](https://drive.google.com/open?id=0BzpiEtMtHC3rUFBPZlBhT0poTWc)

### Party Index

![party index](https://user-images.githubusercontent.com/1119621/28336524-52a3116a-6bd0-11e7-904c-69b0b7980372.png)


### Add Party Modal

![party index_ add party modal](https://user-images.githubusercontent.com/1119621/28336534-5883301a-6bd0-11e7-807c-a4e32a774097.png)

**Comment by clash99** [comment]
Link to start of functional specs:  https://drive.google.com/open?id=1ySPJCYRnf0CKYh6igaclD2N8JdBKuqmScS7OU5KK4sE

**Comment by clash99** [comment]
@dpalomino and @laura-barluzzi - One thing I should note is that this task is to add parties to the party index without being party of a relationship.

A natural progression is for a user to be able to add a relationship/location once viewing a party but I think due to time constraints, we should tackle that at a later date. Adding parties to the party index will allow them to appear in the dropdown when adding a relationship to a location. I believe that is an acceptable workflow. Let me know if you disagree.

### Parties listed in dropdown when adding a relationship to a location
<img width="620" alt="screenshot 2017-07-13 10 19 38" src="https://user-images.githubusercontent.com/1119621/28336946-e336ccfc-6bd1-11e7-863f-24e6b3297b41.png">

**Comment by dpalomino** [comment]
Hey @clash99!

Nice wireframes, as always :-) 

> @dpalomino and @laura-barluzzi - One thing I should note is that this task is to add parties to the party index without being party of a relationship.
> 
> A natural progression is for a user to be able to add a relationship/location once viewing a party but I think due to time constraints, we should tackle that at a later date. Adding parties to the party index will allow them to appear in the dropdown when adding a relationship to a location. I believe that is an acceptable workflow. Let me know if you disagree.

Totally agree. I think that workaround is totally acceptable for now. 

Thanks!

**Comment by clash99** [comment]
Decision record is in-progress here:  https://github.com/Cadasta/decision-records/blob/DR_0012_adding-party-without-relationship/DR_0012_add-party-without-relationship.md

**Comment by laura-barluzzi** [comment]
Hi @clash99, at a first look I think I agree with your proposal of showing the dropdown list of existing parties (which would display also those created from the party index in `template/party/party_list.html`. However, I wouldn't remove the option to do what already happens -- I'd try just to "add" this new way of adding a party rather than removing the existing way. In other words, in the "ADD RELATIONSHIP" modal I would allow the user to choose an existing party _**or**_ type in a new one (as already happens). I am still not super familiar with the `party/model.py` document though so I still have to come up with a clear way to work this out -- I need more playing/reading! :)

**Comment by clash99** [comment]
@laura-barluzzi Yes, agree with above comment. We don't want to change the way to add a party or select existing parties in the relationship area. That should remain the same.

**Comment by laura-barluzzi** [comment]
[UPDATE] Current code work-in-progress is available at my active branch `add_party_without_relationship`
