### ISSUE TITLE
Text Sanitation Needs to Exclude '-' for Latitude, Longitude Fields

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1613]
### Steps to reproduce the error

A partner is trying to upload data from ODK and is running into the `817 - Error: input can not contain HTML tags, emojis or start with any of + = = and @` on 15 records because they contain negative latitudes.

**Comment by wonderchook** [comment]
@oliverroick can you give this a look? I'm wondering if this is an issue with negative numbers as well or if this is being submitted as a text field.

**Comment by oliverroick** [comment]
Will do

**Comment by dpalomino** [comment]
hey @oliverroick, I've done some testing with this. I've used [this project](https://demo.cadasta.org/organizations/david-4/projects/customary-rights-1/) for sending the forms. 

Results: 
- Including negative values in float field returns an error .
- Negative longitude with GeoODK is sent ok (40.32 -3.87 in Madrid) 
- Negative latitude with GeoODK (and positive longitude), -23.24 34.76 **returns an error** >> I think this is why we didn't catch the error, it's only failing with negative latitude and none of us live in the South hemisphere now
- If a text field starts with "-" returns an error (like "-7")
- If a text filed contains a "-" but not at the begging the form then is accepted (like "David-7") >> That's why negative longitudes are not failing and negative latitudes are failing.

**Comment by oliverroick** [comment]
I've opened a PR that fixes the problems with floats and geometries. 

> If a text field starts with "-" returns an error (like "-7")

This is expected behavior. Text inputs must not start with one of `+`, `-`, `@` or `=`. If you need an input for negative numbers then this should be set up as a numeric field.
