### ISSUE TITLE
API 500 Error - "is not JSON serializable"

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1656]
### Steps to reproduce the error

The below error was caused by the QGIS plugin when it uploaded joined tables. I've logged a bug for it in the QGIS repo, but we still shouldn't give a 500 error. Is there a way to make this serializable instead?

TypeError at /api/v1/organizations/chickenville/projects/kate-magical-test-file-2/spatial/
{'have_int': '4', 'name': 'blah blah blah', 'have_dec': '2.100000', 'fake-date': '2017-01-01', 'chickenville/kate-magical-test-file-2/relationships_rel_id': 'x4qc56zp8ybzj5gkxuejinku', 'chickenville/kate-magical-test-file-2/parties_name': 'two', 'chickenville/kate-magical-test-file-2/relationships_rel_name': 'CU', 'chickenville/kate-magical-test-file-2/relationships_party_id': 'awajdc97ktpve6gj6bqrjvwe', 'chickenville/kate-magical-test-file-2/parties_type': 'IN'} is not JSON serializable

**Comment by amplifi** [comment]
This is invalid JSON because it uses single quotes. If the QGIS plugin is submitting this as-is, that's a bug on the plugin side. The API should return a 400 error to indicate invalid data was submitted. We shouldn't try to manipulate submitted data to make it serializable; too many ways that could go wrong.

**Comment by alukach** [comment]
Consistently reproducible here: https://demo.cadasta.org/api/v1/organizations/cadasta-demo-organization/projects/customary-rights-ghana/spatial/

https://opbeat.com/cadasta/platform-demo/errors/169/

**Comment by alukach** [comment]
# Source of the problem

## Where the error comes from


When assembling a response for a web request in JSON format, the DjangoRESTFramework uses the default `JSONRenderer` to serialize `SpatialUnit` to a JSON string. The DRF has a custom encoder that subclasses the stdlib `json.JSONEncoder` encoder.  This custom encoder attempts to convert objects to `dict` classes if those objects have a `__getitem__` attribute:

```py
class JSONEncoder(json.JSONEncoder):
    def default(self, obj):
        # ...
        if hasattr(obj, '__getitem__'):
            try:
                return dict(obj)
            except Exception:
                pass
        # ...
        return super(JSONEncoder, self).default(obj)
```
https://github.com/encode/django-rest-framework/blob/6602171184d8e5c7013407b57bff5745a70733ac/rest_framework/utils/encoders.py#L61-L65

If this casting to `dict` fails, the error is ignored and the data is passed to the stdlib `json.JSONEncoder.default()` method. This method simply throws an error to signify that the data is not JSON-serializable:

```py
class JSONEncoder(object):
    def default(self, o):
        raise TypeError(repr(o) + " is not JSON serializable")
```
https://github.com/simplejson/simplejson/blob/0d36c5cd16055d55e6eceaf252f072a9339e0746/simplejson/encoder.py#L243-L261

This is the error that we are experiencing.


## Why we get the error

### The setup


1. `__getitem__` runs `JSONAttributes.setup_from_dict(self._db_val)`:
    ```py
    def __getitem__(self, key):
        if not self._setup:
            self.setup_from_dict(self._db_val)
        self._check_key(key)
        return super().__getitem__(key)
    ```

1. `JSONAttributes.setup_from_dict` runs `JSONAttributes.setup_schema()`:
    ```py
    def setup_from_dict(self, data_dict):
        self.setup_schema()
        # ...
    ```

1. `JSONAttributes.setup_schema` fetches the related `Schema` instances for the `SpatialUnit` instance runs them through `models.compose_schemas`, and sets the returned general, required, and default `Attribute` instances on to the `JSONAttributes` field instance:
    ```py
    def setup_schema(self, schemas=None):
        if self._setup and schemas is None:
            return

        # Determine schemas for model instance containing this field.
        if schemas is not None:
            self._schemas = schemas
        else:
            self._schemas = Schema.objects.from_instance(self._instance)
        self._setup = True

        # Extract schema attributes, names of required attributes and
        # names of attributes with defaults, composing schemas for
        # instance.
        attrs = compose_schemas(*self._schemas)
        self._attrs, self._required_attrs, self._default_attrs = attrs
        # ...
    ```
    
1. `models.compose_schemas()` basically does a "fetch from cache, if not in cache then fetch from DB and place in cache" lookup for `Attribute` instances associated with the provided `Schema`, if not found it requests them from the db.seems to be that when we run `setup_from_dict()`
1. After `JSONAttributes.setup_form_dict` method stores the returned attributes from `models.compose_schemas` to `self._attrs` and setting the default values onto the `JSONAttributes` field instance (which does not appear to be a factor in this bug), the instance is considered to have been "setup" and we return to `JSONAttributes.setup_from_dict()`.
1. `JSONAttributes.setup_from_dict()` then does a quick check to ensure that all required keys are either present in the provided dict or available as a default attribute (this check does not appear to be a factor in this bug). Afterwards, we iterate through the keys and values of the provided data and check that each key is either in the related schemas instances' attribute (this check does not appear to be a factor in this bug, as all values are already set on `self`) and then we validate each value with the stored `Attribute` instance; afterwards setting the value on `self`.
    ```py
    def setup_from_dict(self, dict):
        self.setup_schema()
        if dict is None or len(dict) == 0:
            self._setup = False
        else:
            self._check_required_keys(dict.keys())
            for k, v in dict.items():
                self._check_key(k)
                self._attrs[k].validate(v)
                self[k] = v
                
    def _check_key(self, key):
        """
        Ensure key is either in the related schemas instances' attributes or
        already set on self.
        """
        self.setup_schema()
        if key not in self._attrs and key not in self:
            raise KeyError(key)
    ```

### The problem

The problem occurs at `self._attrs[k].validate(v)` of the `JSONAttributes.setup_from_dict()` method. It assumes that all the keys of a `SpatialUnit` instance's `attributes` field are known attributes (i.e. the database has `Attribute` instances related to the `Schema` instances that are related to the `SpatialUnit` instance). In all events of serialization failure, the `SpatialUnit.attributes` field has keys that do not have related `Attribute` instances. As such, when casting the `SpatialUnit.attributes` field to a `dict`, `__getattr__` is run and a `KeyError` is thrown.  This error is suppressed by the DRF's `JSONEncoder` and instead a `TypeError` stating that `... is not JSON serializable` is thrown instead.

## Solution

The solution to this bug is likely related to the solution to cadasta/django-jsonattrs/#18.  During testing, I found that cadasta/django-jsonattrs/#30 avoided this bug.

Going to read more and recommend steps moving forward shortly.
