### ISSUE TITLE
Add redirect values to  sign in and register links in header

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1671]
Just an annoyance I deal with each time I am working on a partner account. 

1. I go to an org page. 
2. Unable to access because not signed in. 
3. Sign in. 
4. Taken to homepage. Have to deal with the struggle of finding the project page again. 

Will this be fixed with the new personal dashboard... ?

**Comment by dpalomino** [comment]
Related with #1491. 

I think it will mostly addressed with this subtask for the user dashboard:  

"Returning users will be able to view the specific organizations and projects they are members of as well as their assigned permission level"

As most of real users (not Cadasta staff) will be just dealing with an organizaiton and a couple of projects, I think landing in the dashboard after signing in is going to be sufficient.

**Comment by SteadyCadence** [comment]
This was def an issue when I was sitting next to partners. Everytime their session expired, which seems daily if not hourly, they would go to the URL and then be forced to sign in again and then get taken to the homepage where they had to figure out a way to find their project again.  

 I think the real issue is if someone is logged out and they go to a URL, when they sign back in they should be routed to that same URL.  Other sites seem to be able to support that.  We should as well.  I think I may need to rename this issue to that. "Return to original URL after user signs in"

**Comment by clash99** [comment]
I think this is a bug but can't tell from the description. Can you provide a screenshot or more detail of what page you are on when you link to sign in? Our org pages don't have a register/sign in button like the project pages (minus the header links).

Our site does redirect users back to where they were when they were prompted. Check out a project dashboard not logged in for an example.

**Comment by laura-barluzzi** [comment]
Specifically, this is not going to be "fixed" by the user dashboard. The user dashboard would just reduce the "annoyance" of having to find the organization/project through the whole list of projects since you would access a filtered list on the user dashboard. I think this will fix the annoyance, but itself this issue seems to be related to the fact that you don't return to a page from where you are asked to log-in to access.

Normally, if you try to see one page (let's say the org X dashboard) but you are told "to see the dashboard, login" - if you log-in clicking there you should be returned to that specific org X dashboard. So I'd say this may be a bug.

**Comment by laura-barluzzi** [comment]
Summarizing, if you click on Sign In here, you should land on this project Test Questionnaire instead of the my user dashboard.
![image](https://user-images.githubusercontent.com/16849118/29011917-eaa0ea08-7aeb-11e7-858f-7d6d29d774ab.png)
Still, I think that this issue can be considered closed once the user dashboard is done since the annoyance of re-searching the project would be decreased 100%.

**Comment by amplifi** [comment]
This is a quick fix and has nothing to do with the user dashboard. There's a disparity in the way the "Sign In" button under "Have an account?" on the project dashboard behaves vs the "Sign In" button in the upper righthand corner. The former includes the `next` parameter, the latter does not. If a user clicks the button in the upper righthand corner, they will be dumped back to the dashboard every time. User instinct is to click the "Sign In" button in the upper corner, because that's the first behavior they learn to accomplish this task and that button persists across every page.

We just need to add the `next` param to the "Sign In" button in that top button group.

**Comment by clash99** [comment]
@amplifi Thanks for clarifying bug. I'm filing a PR for this.
