### ISSUE TITLE
Unable to install shapely from requirements

### ISSUE THREAD

**Issue by mish24** [Cadasta/cadasta-platform#1740]
### Steps to reproduce the error
I was running `pip install -r requirements/dev.txt` to manually install all packages. However `shapely==1.5.17.post1` wasn't getting installed at all.

Any ideas why this is happening?

**Comment by mish24** [comment]
Actually upon researching I found out that Vagrant and Virtualbox don't support 32 bit environment. Shouldn't there be a workaround for those environments as well?

**Comment by oliverroick** [comment]
32-bit environments for both [Vagrant](https://www.vagrantup.com/downloads.html) and [Virtualbox](http://www.oracle.com/technetwork/server-storage/virtualbox/downloads/index.html) are supported for all major OS, except Mac OSX. The last version of OSX that you could run on a 32bit system was 10.6, which is unsupported since 2015. 

Supporting outdated systems is a lot of work and it will only provide benefit to a small minority of potential contributors. I think it's not worth to implement a workaround.

**Comment by amplifi** [comment]
Unsupported; closing.
