### ISSUE TITLE
Org names should be case insensitive

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1745]
### Steps to reproduce the error

1. Add an org named "david_organization" for instance. And organization is created with the slug "david_organization"
2. Try to add another org with the same name but different capitalization: "David_Organization". A new organization is created with the slug "david_organization-1"

However, if we try to add "david_organization" again we get an error message preventing us to create an org with the same name. 

### Actual behavior

See above. 

### Expected behavior

Organizations names should be case insensitive

**Comment by amplifi** [comment]
Same bug for projects.

**Comment by valaparthvi** [comment]
@dpalomino Tell me if I understand this correctly.
1) There already exists an organization named `david_organization`.
2) I try to create a new organization `David_Organization`. 
**Expected Behavior**
An error is thrown `Organization with this name already exists.` and organization is not created.

Does that sound right? And the same behavior is expected for projects and also when a user tries to update org/project name, correct?

**Comment by dpalomino** [comment]
thanks @valaparthvi!

> Does that sound right? And the same behavior is expected for projects and also when a user tries to update org/project name, correct?

Exactly, that's the expected behaviour.  

> Now, is it alright if all organization/project names are converted to lower-case before saving them? Or do we want the name to be stored in the way user enters them?

Yes, I think it's good to convert the names to lower-case before saving them. Thanks :-)

**Comment by valaparthvi** [comment]
@dpalomino  I talked to Oliver earlier and he said that we should save the org/project names as entered by the user, and not convert them to lowercase, so I found an alternate solution. Org/Project name will be stored as it is(as entered by the user), but we filtering will be case-insensitive. I am creating a PR, I'm hoping it would make more sense once you review it.
