### ISSUE TITLE
Org admins are public users in org projects by default

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1754]
### Steps to reproduce the error

This was originally detected when testing the replacement of tutelary branch, and we thought it was something related with this. But now I'm seeing this error again. 

1. Login in staging as a user being an org admin for at least one org (dpalomino in my case) 
2. Go to permissions page: 

![screen shot 2017-08-29 at 18 11 02](https://user-images.githubusercontent.com/17198051/29831437-7659465c-8ce5-11e7-97b3-c5c562eda06d.png)

3. Admin is public user by default in all projects. 
4. If a new project is created, then that member will be a public user as well. 

Is this issue something specific with staging env? 

However, if we create a new org then new projects within that org, then behaviour is ok. 

### Actual behavior

See above

### Expected behavior

Org admins should be PM for all projects.

**Comment by seav** [comment]
This seems related to #1752. We have similar screenshots of being shown as an Administrator for the org, but the project permissions/roles are shown as drop-downs. The correct behavior is that these drop-downs should not be present and the roles are fixed to "Administrator" like in the following screenshot.

![screen shot 2017-08-30 at 00 35 41](https://user-images.githubusercontent.com/873653/29832593-542e80c0-8d1b-11e7-99be-716e5299331a.png)

**Comment by amplifi** [comment]
@dpalomino This doesn't match what's on staging or in the db; see screenshot below. I can't replicate the views you're seeing. Memcached was flushed as part of the deployment for the sprint release build, so there's nothing caching permissions on the platform side. Unless somehow you're caching locally? These aren't static assets so that doesn't make sense.

<img width="1052" alt="screen shot 2017-08-30 at 3 28 25 pm" src="https://user-images.githubusercontent.com/4269749/29877622-09e688d2-8d98-11e7-8bfa-0a897ae112b8.png">

**Comment by dpalomino** [comment]
Hi @amplifi. I think @oliverroick was taking a look to this and now it's working fine also for me. I think it was something related with the permissions branch but I don't know details.

**Comment by amplifi** [comment]
@dpalomino Nothing's been changed since you filed the issue; @oliverroick already checked with me about this one. `David Org` has been configured correctly on the server since deployment of the release branch. It's either a local browser caching issue (outside our scope) or an artifact of prior testing related to #1544.

**Comment by dpalomino** [comment]
um, very weird. I will take an eye on this in the next deployment either in staging or production. Thanks for checking @amplifi!

**Comment by oliverroick** [comment]
This issue is related to the permissions branch. The culprits seem to be [this](https://github.com/Cadasta/cadasta-platform/pull/1667/files#diff-c7fb55a37d035d4e6c2df4f098a5553d) and [this](https://github.com/Cadasta/cadasta-platform/pull/1667/files#diff-ef71d660b2376ee7607060717052c9fd) migration. 

The first migration creates a permissions group, which grants admin permissions to an organization role, the second drops the `admin` field from `OrganizationRole`. There are no backward migrations in place. When you want to roll back the migrations, the field `admin` is added back to the table in but not set to `True` for org admins. 

Information on organization roles is stored in `OrganizationRole` objects, but permissions are granted via Tutelary. That explains that you still have admin permissions (because these were not touched by the migrations) but the roles itself are incorrect. 

So the project roles are displayed correctly according to what is in the database. When you look at organization roles of users other than yourself, the org role is also displayed correctly according to what is in the database. 

When you look at your own permissions your org role is displayed as an org admin because this is a special case: The tutelary permission set grants you admin rights on the organization, so you can access the view. The view code assumes that when you have access to the view, you must be an admin of that org (otherwise you wouldn't be able to view it). And because, as an org admin, you're not supposed to change your own role in an organization the view always shows the "Administrator" label and never the form field. Hence the confusion. 

So this explains this bug and why the roles are shown the way they are in #1752. It doesn't explain though, why Eugene wasn't able to archive a project he created.
