### ISSUE TITLE
Feature Toggling

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#18]
It seems like it might be a good idea to have “feature toggles” where we (or PM+s?) can switch more complex features (as we develop them) on or off at a project level. This will also make life a bit easier for testing, since we can roll new features out to guinea pig projects first, rather than dropping new stuff on everyone at once.

**Comment by ian-ross** [comment]
Some links about this:

 * http://martinfowler.com/articles/feature-toggles.html
 * https://en.wikipedia.org/wiki/Feature_toggle
 * https://github.com/danillouz/feature-toggle-react

There seems to be some confusion and argument in some circles about "feature toggles vs. feature branches".  I'd recommend that we continue to use feature branches for feature development, but use feature toggles to control deployment and visibility of features to users.  (The main argument that seems to be used against feature branches is that they can lead to big and difficult merges, but that can be avoided by good communication and frequently rebasing feature branches onto the current master and fixing merge conflicts as they arise, rather than leaving fixing conflict to the final PR creation for merge into master.)

**Comment by wonderchook** [comment]
@amplifi something we were thinking about a while back. Perhaps still relevant. Do you have ideas or thoughts?

**Comment by wonderchook** [comment]
closing this, can reopen later if relevant
