### ISSUE TITLE
[Phone-login] Improve error handling in TwilioGateway.send_sms

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#1897]
Not a bug but an inconvenience when debugging on production environments. 

When [sending a text via the TwilioGateway](https://github.com/Cadasta/cadasta-platform/blob/additional-login-options/cadasta/accounts/gateways.py#L21-L31), we're currently catching all `TwilioException ` and return the error message.

A `TwilioException` could be anything, from the server not being responsive to the wrong authentication credentials, so it could be our fault or Twilio's. 

As far as I know, the error message is not used anywhere (to inform the user when something went wrong; @valaparthvi correct me if that's not the case). The exception is swallowed; from the user's perspective it looks like everything went through successfully except the text might not have been sent. 

We have two options:

1. We remove the `try..except` block and let this fail with a lot of noise. This will result in a platform error and we will be notified accordingly.
2. Handle the error but relay information to the user that something went wrong. In that case, we need to log the incident and notify developers so they can look into the problem.

**Comment by valaparthvi** [comment]
I like the second idea better. We log any error that we may encounter. Every Twilio exception has an error code linked to it, so that makes it easier to detect the issue.Twilio has listed error codes and errors linked to it [here](https://www.twilio.com/docs/api/errors). But I'm not sure how you plan on notifying the developers about it.
