### ISSUE TITLE
Improve instruction/error messaging around urls

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#259]
Suggest adding help text for user or having default "http://" already in field.  Current field error messaging is not user friendly.

![screenshot 2016-06-22 16 24 29](https://cloud.githubusercontent.com/assets/1119621/16284221/d0fcc110-3895-11e6-908c-7a39fc9b0794.png)

**Comment by seav** [comment]
Observation: Both the add organization and add project have this URL field. The add project form uses `type="text"` as the input element attribute while the add project form uses `type="url"`. The above error message is produced by the platform while a similar error for the add project form will produce a browser-based error message ("Please enter a URL."), which I can't get a screenshot of because it disappears whenever I switch windows or press any key.

I'm not sure which we should adopt for the URL field: native browser-based validation or Django-based validation.

**Comment by clash99** [comment]
Added placeholder text "http://"

**Comment by clash99** [comment]
I'm going to turn off browser validation for now so that we aren't getting these types of mulitiple error message:  
![screenshot 2016-07-07 11 20 32](https://cloud.githubusercontent.com/assets/1119621/16661617/5f10e20c-4439-11e6-95bb-b55d988042b9.png)

I will be adding a novalidate tag at the form level.  In the future we should rework client-side validation on all forms.
