### ISSUE TITLE
Add gif to acceptable resource file types

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#279]
I think we should accept gifs since some text documents and photos might be saved in this format.  Are there others?

**Comment by wonderchook** [comment]
pdf, mp3, mp4, doc, docx, jpg, png is what I did by default but you are right gif should also be accepted. 

@fhpichel + @nastynoel other file types that are important to start?

**Comment by nastynoel** [comment]
Tiff, xlsx. Latter could come into play with lists for community mapping
for example.



*From:* Kate Chapman [mailto:notifications@github.com]
*Sent:* Wednesday, 29 June 2016 2:48 AM
*To:* Cadasta/cadasta-platform <cadasta-platform@noreply.github.com>
*Cc:* nastynoel <ntaylor@cadasta.org>; Mention <mention@noreply.github.com>
*Subject:* Re: [Cadasta/cadasta-platform] Add gif to acceptable resource
file types (#279)



pdf, mp3, mp4, doc, docx, jpg, png is what I did by default but you are
right gif should also be accepted.

@fhpichel <https://github.com/fhpichel> + @nastynoel
<https://github.com/nastynoel> other file types that are important to
start?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Cadasta/cadasta-platform/issues/279#issuecomment-229109620>,
or mute the thread
<https://github.com/notifications/unsubscribe/AOLqSiPVLIlB-L0l4g0E4XcoD2AVutlKks5qQVBGgaJpZM4JATVM>
.
