### ISSUE TITLE
Connect map click on project overview to map tab

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#325]
There appears to be a link on the project overview map that goes nowhere.  We should link it to the project map tab.  (The cursor change isn't showing in the video for some reason.)

http://screencast.com/t/huj7c02InW

**Comment by seav** [comment]
This is not actually a link. The default behavior of Leaflet is to change the cursor to a pointer over overlays (markers, shapes) on the map. But the suggestion to link this to the map tab is still valid.

**Comment by seav** [comment]
@clash99, because of the updated map objects styling introduced in PR #396, the project boundary is now just an outline. You still get the pointer cursor when you hover the mouse pointer over the boundary, but this is less likely to be seen by the user because the outline is narrow.

What do you suggest we do now?
1. Make the cursor normal when the mouse pointer hovers over the outline
2. Still add a link from the outline on the project overview tab to the map tab

**Comment by clash99** [comment]
@seav - I see what you mean, its much better since that PR.  I think all we need is to make the border cursor not look linked.
