### ISSUE TITLE
The 180th meridian problem

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#333]
Basically, our platform website will not be able to nicely display project extents or locations that span the 180th meridian. And if we have projects that have locations on either side of the 180th meridian, users would potentially need to go around the world to access both locations. See this [OpenStreetMap wiki page](http://wiki.openstreetmap.org/wiki/180th_meridian) for similar problems encountered in OSM-related tools.

For example, if we have a project on the island of Taveuni, Fiji, we may hit this problem. See the following screenshot showing two Fiji locations next to each other but on opposite sides of the 180th meridian.
![screen shot 2016-07-07 at 12 58 41](https://cloud.githubusercontent.com/assets/873653/16642965/b6171a68-4442-11e6-9463-dc860216eb98.png)

**Comment by seav** [comment]
Here's another example. Drawing a small rectangle that includes the 180th meridian will result into a world-spanning rectangle instead.
![screen shot 2016-07-07 at 20 28 12](https://cloud.githubusercontent.com/assets/873653/16653106/7bdb618a-4481-11e6-8db6-9304d16f75c1.png)

**Comment by linzjax** [comment]
Yikes. I'm fixing the way spatial unit's geometry is set up currently, so I'll address this.

**Comment by ian-ross** [comment]
Doing this 100% reliably is more difficult than you might think.  I've done something similar before (for a weird climate model data preparation tool: https://github.com/ian-ross/isla) and it took a *long* time to get it just right.  For drawing rectangles, the situation is inherently ambiguous: if I give you the "east" and "west" edges of a rectangle that crosses the dateline, for instance, there isn't a canonical direction to draw the rectangle in.  You end up using heuristics (generally, the right direction is the one that gives you the smaller rectangle), but that's not very satisfactory.  @linzjax If you're going to do this, think carefully about how you want it to work before you start trying to code up a solution, otherwise you'll end up flailing (I did...).

**Comment by linzjax** [comment]
So this is happening during the saving stage, not the drawing stage. I think the weirdness of this is cropping up from my hacky fix to things not being centered. It was originally something like:
```
While point > 180:
    point -= 360
While point <= -180:
    point += 360
```
which works if it's a point, but if it's a rectangle it just takes one side and shoots it across to the other, leaving the one that's totally find on the other side of the map.

Unless there's something more complicated that I'm missing.

**Comment by ian-ross** [comment]
No, you're exactly right about what's happening.  Coming up with a good approach to fix it is difficult though.  One option might be to constrain longitude values to (-360, 360] instead of (-180, 180], since you can then represent all "real" longitudinal spans (i.e. less than or equal to one circuit around the world) in a canonical way without ever getting things flipped round.  How that would work with your centring fix, I can't immediately see.  It also depends on how Leaflet deals with drawing polygons that cross the date line.  When I did this in the thing I mentioned, I had to write a completely custom map rendering UI, so I was able to deal with these issues right from the start, but you might need to experiment to make it nice for Leaflet.

**Comment by oliverroick** [comment]
I don't think this is an issue we should address right now. We should shelve that for later

**Comment by ian-ross** [comment]
I agree with Oliver.  It's an edge case that's extremely hard to do correctly.

**Comment by wonderchook** [comment]
Moved off to a later milestone.

**Comment by seav** [comment]
Just a note about Leaflet: Its longitude coordinate system seems to be infinite and not bounded to ±180°. If you place a marker at 345°W, it will place it there and not at the canonical 15°E.

**Comment by oliverroick** [comment]
Should we even try to fix this? It's a very complicated issue and unless we have a project in the north-eastern part of Russia this will never be a problem.

**Comment by ian-ross** [comment]
My vote would be for quietly closing it and never talking about it again.

**Comment by seav** [comment]
It's unlikely we will have a project in Russia. But a project in Fiji is much more possible.

**Comment by ian-ross** [comment]
That's true.  Let's fix it when we have a project in Fiji!

**Comment by seav** [comment]
I agree that fixing this is not a top priority. But do we close this now? What is the disadvantage of keeping this open?

**Comment by wonderchook** [comment]
I think we just kept this open and unscheduled.

**Comment by dpalomino** [comment]
Very low prio issue, closing for now. Please reopen if needed.
