### ISSUE TITLE
Demo Site Deployment Bugs

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#337]
This ticket is to track deployment bugs for the demo site. 

- [x] Can't upload xlsform
- [x] Can't upload resources

^^^^^^ These are probably related but should be tested separately. 

- [x] 500 Error after registering a new user. (User is created and can sign in)
- [x] Unicode is not being handled correctly (possibly a locale setting problem or conflict)

**Comment by amplifi** [comment]
Resolved: 500 Error after registering a new user. AWS has enabled our production use of SES, so new user confirmation emails can be sent to non-cadasta.org domains. This fixes the 500 error upon new user registration with non-cadasta.org email addresses.

**Comment by amplifi** [comment]
Resolved: Can't upload xlsform and can't upload resources. S3 storage configuration complete with django-buckets package.

**Comment by amplifi** [comment]
The "Unicode not being handled correctly" issue and #393 are the same root cause. When an error message includes non-ascii text, uWSGI fails to write it to the log; this generates the unicode encoding error. We can clean up the initial errors that occur in both instances, but any error in similar circumstances will 502 until uWSGI utf-8 logging is sorted.
