### ISSUE TITLE
Location view should zoom to the extent of the geometry

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#377]
When looking a locations within a project, the map should zoom to the extent of the geometry. This seems to work for point / multiple points but is at incorrect zoom level for polygon geometries.. user needs to zoom out to see full polygon extent.

**Comment by seav** [comment]
OK. I think this is a bug in Leaflet. The current code has the following summarized code:
```javascript
var data = LOCATIONS_DATA_AS_GEOJSON;
var geoJson = L.geoJson(null, {onEachFeature: SOME_FUNCTION});
geoJson.addData(data);
map.fitBounds(geoJson.getBounds());
```
This _roughly_ fits the locations into the map view, but some parts at the fringes are cut off.

However, if I replace the last line with either of the following options (basically creating a pristine `L.geoJson` object), the map view displays correctly:
```javascript
// Option 1
map.fitBounds(L.geoJson(data).getBounds());
// Option 2
var newGeoJson = L.geoJson();
newGeoJson.addData(data);
map.fitBounds(newGeoJson.getBounds());
```
I'm applying the Option 1 workaround to the platform.

I would have liked to report this [upstream](https://github.com/Leaflet/Leaflet) but since Leaflet is gearing up for a v1.0.0 release, I doubt this bug (which occurs in Leaflet v0.7) will get fixed.
