### ISSUE TITLE
Clean-up Loading of Static Data Set-up

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#383]
Clean-up process for loading of static data including:

- [ ] Attribute types for jsonattrs
- [ ] Country boundaries
- [ ] Policy documents for tutelary

Others?

**Comment by ian-ross** [comment]
This is pretty much done.  There's now a `loadstatic` management command that loads all of this in an idempotent way.  We'll need to be careful of *changes* to this static data in future, since we'll need to write data migration scripts for the production site, but as far as this issue is concerned, I think we're done.
