### ISSUE TITLE
XForms need a unique way to identify associated questionnaire.

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#440]
The form in ODKCollect needs to know which questionnaire it’s going to so it knows which project to submit to. The only identifiable things sent in the request from ODKCollect are the form_id (questionnaire.string_id), and the file name (questionnaire.name). The form_id does not have to be unique (which makes it problematic), and at least in dev the file name doesn’t have to be unique either… sooo I’m open to suggestions, but I think that’s going to be an issue.

**Comment by wonderchook** [comment]
@linzjax in production with the S3 buckets the file name would be fine, right? @oliverroick any suggestions on how we should manage in dev?

**Comment by oliverroick** [comment]
We could make the `FakeS3Storage`, which we use in the dev environment, create the same random file names that the production `S3Storage` uses. In fact, it's a good idea to do that to make the `FakeS3Storage` behave more like the `S3Storage`.

Would that solve the problem? I add this to the next django-buckets release.

**Comment by bjohare** [comment]
Some thoughts/questions for discussion about xforms implementation:

- I think form submissions should always go to ```project.current_questionnaire```. I don't think it makes sense to allow the user to list out all the questionnaires that have been uploaded for a particular project and select one to submit, they should always be submitting to ```project.current_questionnaire``` (at least for now until we have more understanding of what multiple forms per project means in practice). 
- If we are allowing data collectors to submit any form associated with a project, then ```project.current_questionnaire``` makes no sense.

- I'm not sure that allowing duplicate ```id_strings``` is a problem (duplicate titles might be because they appear in ODKCollect). We want to have the idea that org-admins can '*update*' a form. In reality what this means is that the amended form is uploaded, the version number is incremented, the form is set as ```project.current_questionnaire``` and a new attribute schema is generated. The original xlsfile, questionnaire and attribute schema are not updated in any way. So should the user have to update the ```form_id``` every time they want to update the form?  This caused a fair bit of confusion on the CKAN platform, from the users point of view they're just incrementally updating the same form. This gives us a kind of version control for forms. A completely different form expresses a different data collection 'intention' and so should have a different ```form_id``` (should probably be a different project in fact.)

- We're already generating several unique ids for each uploaded form; ```id, name, md5_hash``` and shouldn't really be looking up questionnaires by ```id_string``` or ```title```. 

- The current implementation of ```md5_hash``` on the questionnaire model doesn't make sense because we allow duplicate ```id_strings``` so the hash is not guaranteed to be unique and it should be updated to include the ```questionnaire.name``` as part of the hash.

- Should ```questionnaire.name``` not be renamed to ```questionnaire.filename``` to reflect the fact that the value comes from the buckets filename?

- When a form is uploaded and parsed in the questionnaire manager, we should insert a node into the xml-form dom with the value of the ```md5_hash```, something like:
 ```xml
<meta>
    <instanceID>uuid:b3f225d3-0fac-4a0b-80c7-60e6db4cc0ad</instanceID>
    <questionnaire_md5hash>2d2636d955e47f5e72e6ea3ee0c6046e</questionnaire_md5hash>
</meta>
```
This will be sent back to us during submission, we can pick it out and use it to lookup the questionnaire and the associated project to submit to.

**Comment by ian-ross** [comment]
All of this sounds really sensible.  I can understand that there are use cases for having multiple distinct questionnaires for a project, but there needs to be some thought about exactly how that should work in terms of data collectors selecting the questionnaire to use (maybe they can be assigned a default questionnaire by the project manager depending on the type of data they're expected to be collecting?).  Until there are clear requirements and a clear design for how that should work, I think the `current_questionnaire` approach is the right one to use.

**Comment by wonderchook** [comment]
Yes, there are use cases for having multiple distinct questionnaires as @ian-ross mentioned. We don't need to support that now and there does need to be more thought put into it. In that scenario I could imagine a situation where the people collecting tax info about a property do it separately than those collecting party information. At least one existing process we've looked at does that.

**Comment by bjohare** [comment]
Looking more closely at the [ODK XForms Spec](https://opendatakit.github.io/odk-xform-spec/#preloaders---metadata) it looks like inserting arbitrary elements into the ```<meta>``` tag (see above) is not the way to go. Instead we should insert a ```version``` attribute into the document root of the xforms instance: https://opendatakit.github.io/odk-xform-spec/#instance:

```xml
<instance>
    <ekcjvf464y5afks6b33qkct3 id="jurassic_park_survey" version="20160726101312">
    ...
</instance>
```
The version timestamp can be incremented for each update to the form and can be used to order the forms in a later version of the [XFormsList API](https://bitbucket.org/javarosa/javarosa/wiki/FormListAPI) (if required). 

For now, the latest version of a particular form will always correspond to ```project.current_questionnaire```.

Instead of applying a **unique** constraint on ```questionnaire.id_string``` there should be a **unique_together** constraint on ```questionnaire.id_string``` and ```questionnaire.version``` (the ```id``` and ```version``` attributes in the example above). 

When forms are submited the questionnaire can be uniquely identified using these ```id``` and ```version``` attributes.
