### ISSUE TITLE
Default is not empty in dropdowns 

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#445]
More of a question - I'm concerned that many of our form selection dropdowns are by default populated with the first option and not an empty default.  This means no errors are flagged when submitted and users could inadvertently be submitting a form field that wasn't truly selected.

**Comment by seav** [comment]
Reopening as there are still some select boxes that have non-blank defaults, such as the organization and members permission for the add project form. Some of them may also need further discussion. For example, setting "Public User" as the default for the member permission might be OK because you don't expect a project creator to explicitly set the permission of ALL organization members.

**Comment by seav** [comment]
Inventory of relevant dropdown/select form fields in the platform and the expected action for each:

**Will be modified to have a blank default value:**
* [ ] Organization selection form field when adding a new project (but, if the number of organizations is just one, no blank value will be added)
* [ ] Location type form field when adding a new location

**Already fixed:**
* Party selection form field when adding a new tenure relationship — already fixed in PR #646
* Party type form field when adding a new party while adding a new tenure relationship — already fixed in PR #646
* Tenure type when adding a new tenure relationship — already fixed in PR #620

**Will not be modified:**
* Org member project role permission fields when adding a new project — "Public User" will be the default value; the project creator cannot be expected to explicitly set the permissions of *all* org members especially if they are many
* Any dropdown/select form field when editing an object — these should already reflect the actual values

**Comment by seav** [comment]
I found a bug where the initial org logo does not match the initially selected org (see screenshot below). This is because the list of orgs is filtered to those the user has the `project.create` permissions for, while the initial org logo defaults to the first org by name regardless of permissions. Resolving this current issue should also fix this bug because there won't be an initial org logo anymore.

![screen shot 2016-09-20 at 16 44 29](https://cloud.githubusercontent.com/assets/873653/18663612/cbee488a-7f51-11e6-8abd-165adcdb2959.png)

**Comment by seav** [comment]
I found another bug where if the initially selected org has no logo, the `<img>` element for the logo is never rendered, and therefore, no logo appears even if the newly selected org does have a logo. This bug will also be fixed when this current issue is resolved.
