### ISSUE TITLE
Adding New Location - Drop Down Pulling from Name instead of Label

### ISSUE THREAD

**Issue by fhpichel** [Cadasta/cadasta-platform#478]
Using the generic Cadasta excel form, it seems the drop down lists are pulling from the "Field Name" as opposed to Field Label, which will cause confusion when doing data entry from the PC, particularly when the name isn't obvious.
![error_excel_namelabel](https://cloud.githubusercontent.com/assets/14877933/16983725/84788940-4e76-11e6-9e11-d2faa8f214e0.png)

![error_label](https://cloud.githubusercontent.com/assets/14877933/16983732/87f95b1c-4e76-11e6-8f3b-77638d8d4a60.png)

**Comment by bjohare** [comment]
Seems to be fixed.

**Comment by dpalomino** [comment]
Hi, 

Unfortunately this issue has appeared again. The 'select_one' fields are drop-down menus are pulled from 'name' column instead of 'label' field. However this is not affecting to the predefined fields  like 'land_type' but to all others defined in the xform.

This is only happening through the web interface. Via GeoODK is working fine. 

Screenshot: 
![screen shot 2016-09-17 at 18 55 37](https://cloud.githubusercontent.com/assets/17198051/18608495/60b37fb8-7d08-11e6-847f-1db944151282.png)

**Comment by wonderchook** [comment]
@dpalomino maybe this was never fixed. Will see about getting it fixed for Monday release. 

As an aside is there a reason you aren't using abbreviations for the data in the dropdowns? Using numbers as you have isn't really good database design, when people export their data from cadasta it will be difficult to use that data. I'd suggest using something similar to have you've spelled out gender.

**Comment by dpalomino** [comment]
Thanks @wonderchook. 

Partner is using these numerical codes for their existing data collection process, so we were just trying to follow their same formats and notations. Meanwhile until this would be fixed, we are going to chance this to be more human readable. Indeed that's why we realised that we had an issue, because for the other fields the 'name' and the 'label' were really similar and this is only happening in the web interface. 

Please, keep in mind that this issue is NOT happening for the mandatory fields like "land_type", "tenure_type", etc.
