### ISSUE TITLE
Rationalise view testing approaches

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#488]
There are currently (at least?) three different approaches used to unit testing of views.  We should settle on one approach, convert all the tests to use it, and document the approach we're using.

**Comment by oliverroick** [comment]
I did a review of our existing test code this morning. Here's what I found along with a recommendation how we could proceed.

## Observations

- We have different ways to setup test for API views and UI views. For instance, API views use DRF’s `APIRequestFactory` to setup requests whereas UI views use `django.http.HttpRequest`. Can we find a way to make this consistent?
- Despite some effort to DRY-out boilerplate code from the tests, many of our test classes contain similar code for setting up models, requests, and views, and rendering templates. 
- In other areas, we took DRY-ing out test code too far. While I agree that we should minimise the amount of boilerplate code wherever possible, I don’t think it is a good practice that we spread the test setup and test assertions across several classes and files. An example is the [SpatialUnitDeleteAPITest](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/spatial/tests/test_views_api_spatial_units.py#L205), which doesn’t have a single method. It extends two classes, one of them has two more ancestors. If this test fails, it’s tedious to track down what went wrong. The test setup is spread across many classes, and we first need to figure out the test case (i.e. request method, data posted, the user authenticated with a request) in order to understand what is tested. If assertions are placed in different classes (even different methods within one class) you need to trace back where the faulty test came from. I agree with what _Two scoops of Django_ says: “Tests should be written as simply as possible. If the code in a test or called to help run a test feels complicated or abstracted, then you have a problem.” And I think, we should address that. 

## Proposed approach

When I was working on the records UI and implemented a [base TestCase for views](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/core/tests/util.py). The TestCase class addresses many of the issues I identified with our existing test setup. It removes much of the boilerplate code to setup requests, views and render responses, while providing the flexibility to set up tests with different users and permissions, post data, template contexts, etc. All assertions are placed inside the actual test method.

The tests for [location views](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/spatial/tests/test_views_default.py) demonstrate how the class is used.

I suggest to take this approach, apply it to all of our tests and extend the class wherever necessary. I don’t recommend this method because I wrote it but because I truly believe that this is the cleanest, efficient and most readable approach to testing views. 

The test class still needs some work. We need to make sure it fulfills the following requirements (some of which have been addressed already):

- Test views with different permissions and a way to setup those permissions in the test setup.
- Validate the response for:
    - Correct status code
    - Correct template rendered with the right template context
    - Correct redirect URLs with correct URL parameters
- Test `POST` requests with valid and invalid states. Ideally, you can update a predefined (valid) `POST` payload by providing selected parameters.
- Test views against existing and non-existing models. Model instances are usually identified via a slug or ID, which are provided in the request URL. Ideally, there are default (valid) URL parameters, which can be updated by providing selected parameters.

The original idea was to release this as a separate library, which I can take care of if we decide to go with that option. Additionally, we might have to implement a similar base class for testing API views; that's something I can look into as well when I start converting the test cases.

**Comment by ian-ross** [comment]
I definitely agree that the DRYing has gone a bit far.  I needed to fix tests a few times recently, and it felt like being in a maze of twisty classes, all alike, none doing very much...  I think I'm responsible for some of that, but it needs to be kept under some sort of control.

I also agree with the base test case approach, even though I didn't write it!

In fact, I agree with everything that Oliver said, and I don't think I have much to add.  Using a base test case (where we can push common functionality in tests upwards to get a sort of DSL for view testing in our application) seems like exactly the right thing to do.  And now we have enough tests that we have a good sample of the sort of things that need to be done in tests, which gives a good basis for deciding what should end up in this DSL and what should be specific to individual tests.

**Comment by oliverroick** [comment]
## Progress on porting tests to new approach:

- [ ] `account.test_views_default`
- [ ] `account.test_views_api`
- [ ] `core.test_views_default`
- [ ] `organization.test_views_api_organizations`
- [ ] `organization.test_views_api_projects`
- [ ] `organization.test_views_api_users`
- [ ] `organization.test_views_default_organizations`
- [ ] `organization.test_views_default_project`
- [ ] `organization.test_views_default_users`
- [ ] `party.test_views_api_parties`
- [ ] `party.test_views_api_party_relationships`
- [ ] `party.test_views_api_relationship_list`
- [ ] `party.test_views_api_tenurerelationships`
- [ ] `questionnaire.test_views_api`
- [ ] `resources.test_views_api`
- [ ] `resources.test_views_default`
- [ ] `spatial.test_views_api_spatial_relationships`
- [ ] `spatial.test_views_api_spatial_units`
- [ ] `xform.test_views_api`

**Comment by wonderchook** [comment]
To be merged after the features in the sprint are finished

**Comment by wonderchook** [comment]
I created #653 as a place holder for the remaining items needed for the QGIS plugin.
