### ISSUE TITLE
Adding resources not on page 1 of library broken

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#507]
When I try to connect a resource that is not on page 1 of the library, it overwrites all the other resources and just connects to the ones on that page.  Ideally all the resources selected on every page of the library would be added to the entity.

Video:  http://screencast.com/t/CpzxYuJMA

**Comment by seav** [comment]
I've looked a bit into this and this is caused by the (default?) DataTables behavior. When it manipulates the table pages, it actually removes the rows from the DOM, instead of hiding them via CSS. This means that when the form is submitted, only the visible rows get sent to the server leading to this bug.

I'll see if there's a way to use CSS-hiding instea of DOM manipulation. Otherwise, we need to add JavaScript to place hidden input fields corresponding to the selected resources prior to form submission.

**Comment by seav** [comment]
I checked the [DataTables reference](https://datatables.net/reference/), and there doesn't seem to be any way to use CSS instead of DOM manipulation. Anyway, I think this is done for performance reasons: Loading an AJAX-powered paged table containing 10,000 rows would take a long time to generate the DOM nodes instead of on-the-fly DOM generation as rows are paged in and out.

So adding JavaScript seems the best way to go.
