### ISSUE TITLE
Org overview blank text

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#510]
We should add text for when there is not any viewable projects or members on the org overview page.

For members, we should hide that entire Members section.

Currently: 
![screenshot 2016-07-26 13 29 36](https://cloud.githubusercontent.com/assets/1119621/17150535/7aa47b7c-5335-11e6-912d-e4b9b39a6a64.png)

**Comment by seav** [comment]
For the member list, I'm surprised that it's empty. There should at least be 1 member there: the org administrator who created the organization.

As for the empty project list, this used to contain an "Add a new project" link. But due to #499, this was removed if the user doesn't have the permission. I guess we can add a short text similar to "This organization currently has no (public) projects."?

**Comment by wonderchook** [comment]
I think @seav's suggested text makes sense. Going to move to next the sprint

**Comment by seav** [comment]
@clash99, can you check if the overview text in #510 is good?

**Comment by clash99** [comment]
Looks good @seav - thank you!
