### ISSUE TITLE
UI for Organizations

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#52]
UI for management of organizations.

* [3.0 Organizations - User Flow](https://drive.google.com/open?id=0BzpiEtMtHC3rdXZlYkgyRko4b0k)
* [3.0 Organizations - Wireframes](https://drive.google.com/open?id=0BzpiEtMtHC3rUy1HZUJEMlNiRUk)

**Comment by ian-ross** [comment]
Is this the same as #31?

**Comment by clash99** [comment]
Wireframe phase in progress.

**Comment by oliverroick** [comment]
I was looking at the wireframes when I was thinking about the user roles API. One thing I was wondering about was wireframe 3.2.3. Should it be possible to make a user organization admin on the project level? I think, that should be an option on the organization level only.

**Comment by ian-ross** [comment]
I agree with Oliver.

**Comment by oliverroick** [comment]
I had a closer look the wireframes today and found some issues:

### General remarks

We need designs for “empty states”. That means what will the organisation index look like after the organisation has been created. There won’t be anything to show, like projects display or activity numbers. Ideally, this is the point where we can provide the user with help and guidance inside the application, i.e. answer the question “Now the I have created, what should I do next?”

### 3.1 Organisation Dashboard

It would be nice to show some activity numbers; however, we won’t be able to present those numbers anytime soon. In the first weeks (or even months) there won’t much activity and we have no means to collect activity information, nor will we have time to implement those kind of things anytime soon. 

We should design these wire frames so we can actually implement them during the next sprints, without having to put any place holders on the application. I’m not sure how to best design this, maybe we just show a list of projects and users together with some links to manage those aspects. 

### 3.1.1 Edit organization modal

_Link to new logo:_ Not sure how we will implement this. Do we download the image and store it on our servers or is this a hot link to the logo? The latter solution has some issues: First, hot linking is generally not a good practice. Second, if we plan for hot linking we will need to consider two different ways to handle organization logos. 1. Store uploaded images on our servers, 2. save a link to a hot linked image. While it’s not all too difficult to implement, it can get quite messy — for instance, when we want to provide thumbnails or images in different sizes. 

### 3.2.1 Add project modal

_Project boundaries:_ We should discuss some usability issues with the map here. If kept inside the modal, the map itself will be too small. Users tend to zoom in quite far when tracing features, so they can easily loose orientation on the map when it’s too small. Then we probably need to add some tools as well that might have to go on the map. And finally, we should also plan for some supporting functionality, such as helping users to find where they need to draw on the map. This could be an address search or locating the user’s current position. 

### 3.2.2 Edit project modal

A question regarding the general flow: In the wireframes the flow is List of projects ==> edit project model ==> list of projects. I assume that there will be project detail pages and users should be able to edit project details from there as well? Should we therefore really allow editing the project details from the list of projects or should we streamline to flow so that you can only edit a project from the details page. It’s important to make this flow (just as archiving or deleting) consistent accross the whole platform. 

### 3.2.3 Project permissions modal

- Managing organization admin should not be possible on the project level.
- Options to add and remove users to and from a project are missing. 

### 3.3.1 Add existing user as org member

I would suggest an alternative flow here. Instead of having a text field where you add multiple user names or e-mail addresses, I would use a more structured approach:

1. Find a user by searching for username, email, first or last name.
2. Add the user to the organisation, while also already assigning the roles.
3. Submit and move on to the next user.

It simplifies the whole process; the org admin otherwise has to go back and forth between adding new users and managaing their roles.

**Comment by clash99** [comment]
Good points - thanks for the feedback.  I'm working on the org section now so I will incorporate changes and have a new version to review over the next day or two. 

Here are a few initial questions/comments:

### General - instructional text

I will add some getting-started-type text for empty pages. 


### 3.1 Dashboard

I will document initial release requirements more.


### 3.1.1 Edit organization modal

So it sounds like we should just have the option to upload a logo, correct?  I was recreating what the platform currently has but I will remove the link logo if that isn't an option we want to support.


### 3.2.1 Add project modal

I need to think about the project boundaries a bit more.


### 3.2.2 Edit project modal

Totally agree, working on consistency now and retrofitting where necessary.  I'm moving editing and archiving to be on detail page (org/project), ellipsis to far right of name.  I'm going to put together a ui components-type of document to include all these decisions once they are solidified.


### 3.2.3 Project permissions modal
- Working on org admin permission changes now.
- All organization members are able to see all org projects so once a member has accepted the invitation to join an organization, they will automatically appear in the projects list under the permissions section. 
- Adding and removing member actions are under section 3.3.  Since users have to accept their invitation to join the organization, there is an extra step required for admins to add permissions.


### 3.3.1  Adding existing user

The last discussion I had regarding this issue it was decided that admins could only send invitations to join organizations to usernames or email addresses (no search mechanism, no user list).  I know this seems more tedious but that was the latest decision based on potential privacy issues.  If that isn't the case or the requirement changes then I agree we should rework to have a search and add functionality.  I agree right now it is cumbersome.

**Comment by clash99** [comment]
I've reworked the organization wireframes and have included the following based on your feedback:

### General - instructional text

Added some empty state/ getting-started type text.  Hope to be able to reference get-started videos to simplify the text. 

### 3.1 Dashboard

Added an early release version with intro text.  I agree that perhaps just a simple project list on the left might be the best way to go before data analytics can kick in.

### 3.1.1 Edit organization modal

Removed link to logo option.  Simplified upload file interface.

### 3.2.1 Add project modal

Added large map for project geometry for first step.  Leads to project details and then project permissions for a wizard-approach to creating project.  Everything else done in the project area will actually move user out of organization umbrella and into project detail area.

### 3.2.2 Edit project modal

Solidified the header and side nav areas here:  https://drive.google.com/open?id=0BzpiEtMtHC3rZVlLb3QxNWVrejg.  This should help with consistency as we build out additional pages.

### 3.2.3 Project permissions modal
- Moved org admin permissions to be at organizational level.
- Pending our conversation on Monday, this page may need further revision.

### 3.3.1  Adding existing user

Pending our conversation on Monday, this page may need further revision.


Other:

- Removed bulk actions from the organizations area at this point.  Can revisit in future.
- Simplified interfaces and flows.

**Comment by ian-ross** [comment]
This is definitely getting better (where "better" means "closer to something we can implement right away"!).

However, there's one thing about all of the wireframes that makes me a bit uncomfortable, and that's the ubiquitous use of modals.  Some of these modals are quite big and complicated and don't feel appropriate for representation that way.  It seems like it would be better to have real *pages* for most of these things, reserving modals for simple confirmation dialogues.  (The case that really consolidated this feeling for me was the project extents modal: it just doesn't seem right to pop up a modal with a more or less full-screen map view in it for editing.)

There's also a general principle in UI design that it's better to avoid modal interactions where possible (this is something Jef Raskin really pushed in the original development of the first Mac GUI).  Modals generally don't feel like they fit very well with the navigation model that most web apps use -- they lock the user into doing "one thing right now" and they have to "unstack" from that thing to go anywhere else in the application.  That's generally not the way the web works: you can always click on another link on a page, open another tab from another link on a page, and so on.

As well as making the user interface feel a bit more natural, I think that using pages (perhaps with breadcrumbs) instead of modals has two additional benefits:

1. Distinct pages can be wired up to the URL router in the front-end, so that it becomes possible to bookmark pages.  For example, an org admin could bookmark the "add members" page for their organisation so that they can quickly add new members without having to navigate from the landing page to the dashboard to the organisation index to the individual organisation page to the add members dialogue.

2. Interaction between modals and the browser back button always feels a bit uncertain to me.  Does "back" mean "cancel"?  Or does it mean "back from the underlying page"?  With real pages, it's quite clear: when a new page appears, it goes into the browser history, so the back button works just as you'd expect.  Clicking around breadcrumbs also works fine.

If you want to retain the feeling that these subsidiary pages are somehow overlays on the main pages, we can use transition animations (something like this: http://coenraets.org/blog/2014/12/animated-page-transitions-with-react-js/) to help with that.

In terms of the page flow you've drawn up, I don't think there are any real changes: just replace "modal" with "page" everywhere and I think it still makes sense.  I also think that most of the current modal wireframes can just be "popped out" into pages without any real changes in layout.

For me, the basic navigation model feels like something we should settle on before we start writing any more JS for the front-end.  I'd be interested to hear agruments in support of modals, because maybe there's something I'm just not seeing here.

**Comment by clash99** [comment]
Thanks for the feedback.  You’ve posed some good questions about modals versus pages and there are definitely various schools of thought (some since 1983).  My reasons for recommending modals for specific uses in the Cadasta platform are directly related to past experience with tool development. 

1. Modals are very common in these types of tools because they are fast, focused, contextual interactions.  Our platform is quite complicated in its many sections so I believe this is the best choice over sending the user to new pages for short forms.  In my past experience, we've found that using modals in many instances leads to a improved usability experience since reducing the number of pages has a perceived ease of use. 

2. That being said, I think modals are best used strategically.  Currently the modals are being used for adding, editing, and confirmation actions.  I think we can easily develop best practices where modals should have roughly 6(?) input fields or less.  I understand your concerns regarding the new project modal so I’ve moved that into a page context.  There is always a balance between consistency and flexibility so no doubt this process will present more of these types of questions along the way. 

3. I believe that if we do a good job developing the platform navigation and smart dashboards, a user shouldn’t have to rely on bookmarks within the platform to find pages.  Currently an org admin would arrive at their org landing page/dashboard and select “Add new member” to perform the action you mentioned.  

4. My end goal is to ensure the user journey through our site is intuitive; obviously not to confuse or bombard.  The wireframes serve to demonstrate user flows and hash out these types of ideas.  They can't perfectly replace the true experience of interacting with the tool.  At the end of day our users will be the ones to decide what works.  I’m excited to push to that point where we have the new platform up and running and can start usability sessions.

**Comment by ian-ross** [comment]
@clash99 @oliverroick Can this be closed now?

**Comment by oliverroick** [comment]
@ian-ross I think so.

**Comment by ian-ross** [comment]
OK, closing it.  @clash99 If you think there's anything left to do on this, just reopen it.
