### ISSUE TITLE
Display user's friendly file name for resources

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#533]
### Steps to reproduce the error

Upload a file in resources.  Once uploaded you will notice the name changed from your local name to the s3 name (which is not friendly).

### Expected behavior

I would expect for the user to always see their local file name that they uploaded instead of the s3 file name.  Currently I think its confusing to the user to see what they have intended to upload and would lead them to believe they selected the wrong file.

![screenshot 2016-08-08 13 35 14](https://cloud.githubusercontent.com/assets/1119621/17491541/a9ee9e34-5d6d-11e6-8720-6060deacd1e8.png)
![screenshot 2016-08-08 13 40 52](https://cloud.githubusercontent.com/assets/1119621/17491564/c2840fd8-5d6d-11e6-9fae-dba67362c2e8.png)

**Comment by seav** [comment]
I will partially fix this issue for the table of resources. The filename in the upload resource form is handled by django-buckets so I will leave that to @oliverroick.

**Comment by seav** [comment]
Reopening this because the unfriendly file name will still appear in the upload form:

![image](https://cloud.githubusercontent.com/assets/1119621/17491564/c2840fd8-5d6d-11e6-9fae-dba67362c2e8.png)

This is caused by JavaScript code in django-buckets. I only resolved the unfriendly filenames that appear in our platform.

**Comment by seav** [comment]
OK. There's this little bit that slipped from my mind. When the user clicks on the "Download" button on the resource detail page, he or she gets prompted to download using the unfriendly filename because we link directly to the file uploaded in S3. We should provide the original filename in the [`download` HTML attribute](https://developer.mozilla.org/en/docs/Web/HTML/Element/a).

Current template code:
```html
<a href="{{ resource.file.url }}" class="btn btn-primary" download>{% trans "Download" %}</a>
```

Proposed template code:
```html
<a href="{{ resource.file.url }}" class="btn btn-primary" download="{{ resource.original_file }}">{% trans "Download" %}</a>
```
