### ISSUE TITLE
Resource photo orientation all landscape

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#552]
### Steps to reproduce the error

Upload a resource with a portrait layout.  
### Actual behavior

In platform, all resource photos seem to have landscape layout.
### Expected behavior

I would expect photo orientation in platform to be the same as uploaded resource.

**Comment by ian-ross** [comment]
@clash99 Can you give an example of what you mean here?  I don't really see this: thumbnails for image resources are clipped to square (so portrait/landscape is irrelevant), and when you download image resources you get back the same image you uploaded.

**Comment by clash99** [comment]
I wish I would have attached screenshots so I would remember the details.  I think this was directly to an exercise in Frankfort.  @dpalomino Do you remember any of the details on this one?  I think Noel tried to take photos and upload them and they were flipped.  Is that correct?

**Comment by wonderchook** [comment]
Here is a picture where when you upload it then it is rotated. 

![null-island-article](https://cloud.githubusercontent.com/assets/67992/20114961/4ec8b900-a5ab-11e6-8456-58f1b2873ad2.jpg)

**Comment by ian-ross** [comment]
The EXIF metadata for that image says that its width is 5312 and its height is 2988, i.e. it's a landscape image.

**Comment by ian-ross** [comment]
But then it also has an orientation tag.  Not sure how to interpret that.

**Comment by ian-ross** [comment]
OK, so it looks like the EXIF orientation tag is being ignored.  It's a little weird, but from what I can figure from the EXIF standard (http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf), the settings for that can make "rows" in the image data actually be columns and "columns" rows.  Confusing.  I'll look into what people normally do about this, but I guess the options are either to keep the images as they are and figure out some way to take account of the EXIF orientation information when displaying them, or to normalise the images when they're uploaded so that rows and columns in the image data really are rows and columns in the "real image".

**Comment by clash99** [comment]
![img_2794](https://cloud.githubusercontent.com/assets/1119621/20115576/75aa7258-a5be-11e6-888e-3c4c76a05488.png)
![img_2795](https://cloud.githubusercontent.com/assets/1119621/20115577/75ae48a6-a5be-11e6-81be-0dea197fafd5.png)

**Comment by ian-ross** [comment]
Can you attach the JPEG image itself so I can look at its metadata?

**Comment by clash99** [comment]
![img_2793](https://cloud.githubusercontent.com/assets/1119621/20115759/22fd577c-a5bf-11e6-8ab5-c97f003f8959.JPG)

**Comment by ian-ross** [comment]
So that one's the same: from the image dimensions it looks like a landscape image, but it has an EXIF orientation tag that says it should be rotated into portrait orientation.  I guess most phone cameras give a fixed number of "rows" and "columns" irrespective of the image orientation, and just change the EXIF orientation tag to indicate which way round the camera was being held.

And as you can see from the way GitHub handles the images, we're not alone in ignoring the orientation tags.

**Comment by ian-ross** [comment]
Hmmm.  There's possibly a simple CSS fix for this: https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation  But browser support is pretty non-existent: http://caniuse.com/#search=image-orientation

**Comment by ian-ross** [comment]
Best solution seems to be some JS in the browser to read the EXIF metadata and rotate the images appropriately.  That seems like a better idea than messing with the images as uploaded.  I've seen a couple of examples floating around.  I'll adapt one for our case.

**Comment by ian-ross** [comment]
Ha.  This turns out to be a different problem to what I thought.  It's just a matter of making sure that the orientation information is taken into account when image thumbnails are created: the incorrectly rotated images you're seeing are all thumbnails.  In any case, I'll fix it.  Should be easier than the live in-browser rotation.
