### ISSUE TITLE
Design Data Import UI

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#565]
[Requirements](https://devwiki.corp.cadasta.org/Data%20Import)

**Comment by clash99** [comment]
Fix these:

- Remove question mark from end of label

![screenshot 2016-10-04 13 33 49](https://cloud.githubusercontent.com/assets/1119621/19087442/95ef35fa-8a37-11e6-8eef-620fa75420bc.png)

- Add missing page titles to download data

- Add missing page titles to import data

**Comment by clash99** [comment]
@bjohare - I have some initial ideas for making these difficult pages a little simpler for users to understand.  Here are some recommended design changes for the first two pages.  I have some questions for the third page so I will send those separately.  I haven't implemented the wizard steps yet but have that task slated for next sprint.  

I want to make sure my understanding is correct so please review and let me know if you have any recommendations for improving.

![screenshot 2016-10-06 17 17 17](https://cloud.githubusercontent.com/assets/1119621/19173718/1371a770-8bef-11e6-8f9d-a02b366013de.png)

**Question:**  
- Can we hide the radio button for import type since there is only one value there and we reiterate accepted file types underneath file input?

![screenshot 2016-10-06 17 31 57](https://cloud.githubusercontent.com/assets/1119621/19173721/1a31d0bc-8bef-11e6-9c38-f0abab36c585.png)

**Questions:**  
- Can we move checkbox column to be first instead of last to be consistent with other checkbox tables in the platform?
- Can we hide attributes not found section if it is empty?

Thanks,
Chandra

**Comment by clash99** [comment]
@bjohare - Here is the second pass at data import pages.  

Page 1: 
![screenshot 2016-10-11 14 03 52](https://cloud.githubusercontent.com/assets/1119621/19284462/967fd946-8fbb-11e6-968e-18a9058bfebd.png)

Changes from current version:
- Added sectioning
- Updated field labels to include "import"
- Hid radio button "csv" option since it is automatically selected at this time 
- Hid include as resource option since it is automatically added at this time

Page 2: 
![screenshot 2016-10-11 13 55 46](https://cloud.githubusercontent.com/assets/1119621/19284406/632dfabe-8fbb-11e6-9d9b-5e1a283195ab.png)

Changes:
- Added text instructions
- Added individual warning sections below
- Hid extra_headers or extra_attrs if empty

Page 3:
![screenshot 2016-10-11 14 26 04](https://cloud.githubusercontent.com/assets/1119621/19285178/bb74b5d4-8fbe-11e6-9a00-252f71ef8d55.png)

Changes:
- Added instruction text
- Added section dividers
- Tried to update field labels (still not sure about these - can you make suggestions?)
- Put fields on individual rows since they aren't the same (let me know if you think this is more confusing)
- Changed text on last button to "finish" to match wizard patterns

Outstanding:  Getting wizards steps integrated (slated for next sprint)

Please review and let me know if you have any questions/ comments.  These changes are in branch #565.

**Comment by bjohare** [comment]
@clash99 thanks for this.

#### Page 1

looks good to me..

#### Page 2 

I'm not sure about the text:

> The following fields cannot be imported because they have no corresponding attribute.

Maybe something like this might be more accurate:

> The following fields have no corresponding attribute.

Its not true to say that they can't be imported; fields appearing here could be default fields that will be mapped in the third step. In the sample data there were typos in the csv column names and these `wells` were meant to flag up mismatches between the project schema and the import. Whether we need them or not is debatable..

#### Page 3

I prefer the select boxes arranged inline rather that stacked. I like the section dividers. I think we need to think more about the instruction text and the labels, but probably easier to do this in a call?

**Comment by clash99** [comment]
@bjohare - Thanks for the feedback.  I've incorporated the changes minus the default labels which we can discuss tomorrow.  Let me know if there is anything else...  I think we are getting close!

Page 2:
![screenshot 2016-10-12 10 50 24](https://cloud.githubusercontent.com/assets/1119621/19317572/0b4874f4-906b-11e6-9c4f-85230a9616a9.png)

Page 3:
![screenshot 2016-10-12 10 53 38](https://cloud.githubusercontent.com/assets/1119621/19317581/124c9ffa-906b-11e6-92af-4379f1c2b191.png)

**Comment by clash99** [comment]
One other thought on this one - seems like there should be some sort of index of past data imports available to the user.  Would this be covered under the not-yet-developed activity log page?  Or are there other plans?

**Comment by clash99** [comment]
@bjohare - Any changes here?  I just rebased branch enhancement/#565 was checking to see if its okay to go ahead and do a pull-request or if you were going to roll these into something you were working on.  Just let me know - thanks!

**Comment by clash99** [comment]
Final screenshots with wizard steps:

![screenshot 2016-10-26 10 54 43](https://cloud.githubusercontent.com/assets/1119621/19734144/12e4b87e-9b6c-11e6-8010-fc008591386d.png)
![screenshot 2016-10-26 10 57 43](https://cloud.githubusercontent.com/assets/1119621/19734146/12ecd7a2-9b6c-11e6-8555-b1c30cac8575.png)
<img width="1109" alt="screenshot 2016-10-26 10 58 03" src="https://cloud.githubusercontent.com/assets/1119621/19734145/12e77500-9b6c-11e6-81cb-37ec4b230a07.png">
