### ISSUE TITLE
Review the platform code and templates for untranslatable texts

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#573]
Currently, not all user-facing texts in the platform is translatable. These should be reviewed and then made translatable.

-----

Tasks to do this (marked done when changed in my working branch and pushed to Transifex to test they get extracted properly):

- [x] Page titles
- [x] Copyright notice in footer
- [x] OSM map data attribution (*though not "Geocoding by Mapzen" string...*)
- [x] Pagination and filtering controls on table views: "Search", "Showing 1-10 of 20", "Show 10 rows", "No data available in table"
- [x] "Project overview" on project dashboard
- [x] "Attach" button on project resource list (also in parcel "Resources" panel)
- [x] "Choose file", "No file chosen", "Accepted file types: ..." in file upload modals (*"Accepted file types" done, but I think the others are just down to your browser language choice.*)
- [x] "Zoom in", "zoom out" hover text on Leaflet controls
- [x] Hover text on Leaflet draw controls
- [x] "For assistance with questionnaires ..." on add project details view
- [x] User roles in dropdown on add project permissions view ("Public User", etc.)
- [x] "Add new location" and "Draw location on map" in add location view
- [x] Location type dropdown in add location view ("Parcel", "Building", etc.)
- [x] Party and tenure relationship types in dropdowns

**Comment by ian-ross** [comment]
I've done some work on looking for untranslatable text (and working out how to fix them).  So far, I have the following:

- Copyright notice in footer *[Single string]*
- OSM map data attribution *[Single string]*
- Pagination and filtering controls on table views: "Search", "Showing 1-10 of 20", "Show 10 rows", "No data available in table" *[Configurable in datatables setup]*
- "Project overview" on project dashboard *[Single string]*
- "Attach" button on project resource list (also in parcel "Resources" panel) *[Single string]*
- "Choose file", "No file chosen", "Accepted file types: ..." in file upload modals *[One single string, the others just browser language choice?]*
- "Zoom in", "zoom out" hover text on Leaflet controls *[Should be possible, with some sneakiness in the Leaflet setup]*
- Hover text on Leaflet draw controls *[Not hard, but will need some sort of JS translation setup]*
- "For assistance with questionnaires ..." on add project details view *[Single string]*
- User roles in dropdown on add project permissions view ("Public User", etc.) *[Use lazy translation?]*
- "Add new location" and "Draw location on map" in add location view *[Single strings]*
- Location type dropdown in add location view ("Parcel", "Building", etc.) *[Use lazy translation?]*
- Party and tenure relationship types in dropdowns *[Use lazy translation?]*

Here, "Single string" means it's just a string somewhere in the code that needs to be marked up as translatable.  The dropdown choices are also easy, since it's just a question of switching to what Django calls "lazy" translation for those, so that they get translated when rendering the view (when the language is known) rather than at import time.  The others are mostly strings used by Javascript packages (DataTables, Leaflet, Leaflet.draw).  We'll need to set up some sort of Javascript translation framework, and probably a separate Transifex resource to segregate them from all the Django strings.  And we'll need to do some fiddling around with the setup of these packages to make them pick up the translated strings, but there's not too much to it.

I'd suggest leaving this issue open, and just renaming it to something like "Fix all the translations", which I'll then go ahead and deal with.
