### ISSUE TITLE
During resource upload, resources should be removed when user clicks the 'remove' link

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#582]
### Steps to reproduce the error

Open a project location. Select the _Relationships_ tab, then the _Relationship_ detail view. In the _Resources_ panel click _Add_. Upload a resource without saving the form. Click _Remove_ to remove the uploaded resource. Click _Cancel_.

### Actual behavior

The file remains on our server even though the user has chosen to remove the resource and has cancelled the _Upload Resource_ action. 

### Expected behavior

The uploaded file should be removed from the UI and from S3. 

![remove](https://cloud.githubusercontent.com/assets/3308136/17887042/775f1614-691c-11e6-9e14-1bfef7e71a81.png)

**Comment by seav** [comment]
I've looked at this and this is a limitation of django-buckets. This bug cannot be fixed unless we update django-buckets or use a different widget that uploads files only when the user hits the "Save" button.

First, django-buckets' widget opportunistically uploads files once the user has selected a file and does not wait for the user to hit the "Save" button. I think this is good from a usability point of view. So there should be a way to remove this uploaded file if ever the user decides to cancel the upload.

Second, django-buckets' widget does not provide any way to delete files from S3 once uploaded. The `S3File` object does have the `delete()` method which I assume deletes the uploaded file in S3, but this is not exposed in the widget.

I'll file a bug on [django-buckets](https://github.com/Cadasta/django-buckets/) for this, but I suggest that this not be resolved for now (Sprint 8) since this is not a critical bug. I think the only possible harm that this bug can do is related to privacy where a user may inadvertently upload files that he or she did not mean to upload.
