### ISSUE TITLE
Cannot cancel edit resource if changes are made

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#594]
### Steps to reproduce the error

- Upload a resource.
- Go to the edit screen of that resource
- Remove the file and try to save
- Try to cancel

### Actual behavior
The file reappears and the user is stuck on a loop on the resource edit form.

### Expected behavior
Undo all attempted changes and return the user to the resource detail view.

**Comment by seav** [comment]
How different is this from #582?

**Comment by linzjax** [comment]
The difference is that this is dealing with user navigation once the resource is already loaded, rather than whether or not the resource is uploaded. The user is stuck on the form and cannot cancel out.

They are similar though

**Comment by linzjax** [comment]
![resource_cancel_loop](https://cloud.githubusercontent.com/assets/8128188/17906760/a26e3e0a-6946-11e6-8831-2c345faea6fa.gif)

**Comment by wonderchook** [comment]
@seav can you give fixing this a try?

**Comment by seav** [comment]
This bug is caused by the change of the Cancel button's URL from:
```
{% url 'resources:project_list' object.organization.slug object.slug %}
```
to 
```
{{ request.META.HTTP_REFERER }}
```

The original URL is wrong, but using the HTTP referrer is wrong too because it will cause this looping bug from which there is no hope of escape. Because we can only reach the edit resource page from the resource detail page, I think the proper Cancel URL is the resource detail page.

That said, the current site also has the feature that the edit resource page is reached with a `next` URL query parameter pointing to the HTTP referrer. This is so that when the resource has been edited and saved, we go back to the resource list of the entity (whether project, location, party, or (tenure) relationship) that the user was looking at when he or she decided to edit the resource. So I think this is the more user-friendly URL to use.

I plan to get the `next` parameter and shove that into the Cancel button's URL.
