### ISSUE TITLE
Add New Project Location - Project Extent 

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#598]
### Steps to reproduce the error

* Navigate to Add a new project location
* In the dropdown menu for _What type of location is this?_ I see "Project Extent"

### Actual behavior

(see above)

### Expected behavior

I would not expect to see "Project Extent" listed as a type of project location, as the project extent has already been created when the project area was created. 

![image](https://cloud.githubusercontent.com/assets/3361475/17912026/dc76f728-6945-11e6-9c72-e52af4951a08.png)

**Comment by wonderchook** [comment]
@ian-ross is there an issue way to pull that out?

**Comment by wonderchook** [comment]
Yes, pull out of the drop down.

**Comment by ian-ross** [comment]
I'm not sure what the best way to do this is.  The list of spatial unit types is currently hard-coded here: https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/spatial/choices.py#L4-L12  The "project extent" choice is obviously a bit anomalous there, because it's not a value that can be selected for a user-generated spatial unit.  For the moment, we could just filter it out of the choices manually.  That might be the simplest approach, since in the longer term, I imagine that the list of spatial unit types will be configurable by the project manager.

Would a slightly Rube Golderbergesque manual filtering out of "project extent" for that dropdown be satisfactory for now?

**Comment by wonderchook** [comment]
That was why I thought it might be hard. I think filtering it out for the time being is fine, since we'll be moving to configured types eventually.

**Comment by oliverroick** [comment]
Do we need project extent on that list at all? `Project` has a geometry field for the extent, we won't be using `SpatialUnit` for project extents. This seems to be a legacy from our first drafts of the data model when we thought any geometry would be a spatial unit.

**Comment by ian-ross** [comment]
@oliverroick Did we talk about that?  Maybe we did, and I forgot.  I was still thinking that we would move over to that model of things eventually (all geometry is a spatial unit).  I thought the `extent` field in `Project` was just an interim measure we put in place when we originally wrote the `Project` class, because we didn't have spatial units yet then.  Having all geometry as a single class would make geometry queries a lot easier: "What Cadasta stuff is within 500 km of this point?" becomes a lot easier to answer if there's only one table with geometry in it.

**Comment by oliverroick** [comment]
> Having all geometry as a single class would make geometry queries a lot easier: "What Cadasta stuff is within 500 km of this point?" becomes a lot easier to answer if there's only one table with geometry in it.

This sounds reasonable; I didn't think about that. It that case, we obviously shouldn't remove the item from the list and just not display it when it's not needed. I think the best place to do that is in the form.
