### ISSUE TITLE
Drop down for org admin user should not be active on project permissions page

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#632]
### Steps to reproduce the error

1. Create new project
2. Press "next" from project extent screen
3. Enter Project Name
4. Press "next" 
5. Press "back"
6. Press "next"
7. Drop down for org admin appears. 

### Actual behavior
State of permissions page before hitting back
![add-new-project1](https://cloud.githubusercontent.com/assets/67992/18188568/124e1c7c-7068-11e6-9ebd-c83cbcfd72ee.jpg)
State of permissions page after hitting back then next 
![add-new-project2](https://cloud.githubusercontent.com/assets/67992/18188570/156c2002-7068-11e6-9f57-84cf9e3cf75a.jpg)

### Expected behavior
Permissions page should look the same

**Comment by ApheleiaS** [comment]
Hello, My name is Akanksha and I would like to work on this bug as a first contribution for candidacy for Outreachy upcoming round. I am new to Cadasta and am just setting up the env.  

I was trying to reproduce this bug as reported on this URL : "https://platform-staging-api.cadasta.org/projects/new" as I could see in the bug report. 
However on creating a new project here and typing in the project name and hitting the next key I get redirected to a Platform Error Message. 
Am I not supposed to be able to reproduce the bug this way? And do I have to use my own dev-env for this?

**Comment by wonderchook** [comment]
@ApheleiaS could you type in the exact directions you did to create a new project. Including what you input in so maybe I can help track it down?

**Comment by wonderchook** [comment]
Actually in looking at the errors. Did you create a new organization and username prior to creating the project?

**Comment by hb2002** [comment]
@wonderchook I would like to take this as my first bug towards outreachy. I have reproduced the bug :)
There is one correction, we have to press "Previous" in the page instead of "back" in the browser. That was a bit confusing.
@ApheleiaS You have to create a new organization before creating the project :)

**Comment by wonderchook** [comment]
@hb2002 more than one person can attempt to fix a bug, so please feel free to go for it.

**Comment by divyabiyani** [comment]
@wonderchook I have reproduced the bug.
Could you please let me know where to find the file for this particular section so that I can ammend the code.

**Comment by ian-ross** [comment]
@divyabiyani Because we're using these small issues as a sort of gatekeeper for the Outreachy internships, we can't really give you that sort of open-ended help.  Diagnosing what's causing buggy behaviour is a *really* important skill, in many ways more important than being able to fix bugs once you find them.  It's often the case that you will spend hours tracking down a bug, for the fix to be a one-line change.  And learning to explore a new code base is also really important.  The Cadasta platform code is only about 25,000 lines of Python at the moment, much of which is not very complicated (for comparison, a large project might be 0.5-1 million lines of code).  Reading through the code, identifying where certain things happen, understanding how we use the Django framework, and so on, are all things that are valuable to do in their own right, and will make it very easy for you to answer your question yourself.

(All of the same comments apply to #674 as well, where you made more or less the same request.)

**Comment by divyabiyani** [comment]
@ian-ross Ok Sure I will read the code and try to understand the structure. :smile:

**Comment by ian-ross** [comment]
@divyabiyani Good!  We're happy to answer specific questions, of course, but we need to see that you've done some investigation and thinking of your own before we do that.

**Comment by kavindya89** [comment]
@ian-ross @wonderchook can I attempt to fix this?

**Comment by wonderchook** [comment]
@kavindya89 sure, go ahead!

**Comment by ian-ross** [comment]
@kavindya89 Yeah, you're welcome to have a go.  This might be quite difficult to fix though.  The wizard form controller used for this is slightly tricky to manage.

**Comment by kavindya89** [comment]
@ian-ross @wonderchook thanks I'm proceeding with this.

**Comment by kavindya89** [comment]
@ian-ross indeed it seems bit tricky, I'm continue to investigate on this issue. Will see if I can find the solution :+1:

**Comment by kavindya89** [comment]
@ian-ross @wonderchook is there any possibility I can log and see data coming to a page? I new to django so any help would be appreciated. I found places which it render. Need to see data comes to the page before it render.

**Comment by ian-ross** [comment]
I usually just add print statements somewhere in the view code. The request itself is available as `self.request` within the view and there are various things you can look at within it. Take a look in the Django documentation about the `HttpRequest` class.

**Comment by kavindya89** [comment]
@ian-ross thanks a lot for the input. Getting familiar with Django!

**Comment by kavindya89** [comment]
@ian-ross I have did a detailed investigation on this. We have couple of ways to fix it. I'll summarize it soon.

**Comment by kavindya89** [comment]
@ian-ross I have did a detailed investigation on this. We have couple of ways to fix it. I'll summarize it soon.

**Comment by kavindya89** [comment]
@ian-ross sorry for getting delayed on getting back. The main cause of this issue is, when we navigate back to the project page from permission page, it performs form submission with user permissions. For admin user, there isn't any data submitted. Hence when page rendering back following code get executes for rendering

    def render(self, name, value, attrs=None, choices=()):
        if value == 'A':
            select = _("Administrator")
        else:
            select = super().render(name, value, attrs=attrs, choices=choices)

        return self.html.format(
            full_name=self.user.full_name,
            username=self.user.username,
            email=self.user.email,
            select=select
        )

The value for administrative use is None. If I change if statement like below things works perfectly.

    def render(self, name, value, attrs=None, choices=()):
        if value == 'A' or value is None:
            select = _("Administrator")
        else:
            select = super().render(name, value, attrs=attrs, choices=choices)

        return self.html.format(
            full_name=self.user.full_name,
            username=self.user.username,
            email=self.user.email,
            select=select
        )

I'm not sure whether this this the best place to do it. Otherwise I think we need to do a user permission check ProjectRoleWidget within this class and set the appropriate select value. Any thoughts on this?

**Comment by ian-ross** [comment]
@kavindya89 Can you confirm that this problem still occurs in the latest master?  PR #713 changed some things in the add project wizard that might have affected this.

**Comment by kavindya89** [comment]
@ian-ross just checked with latest update. I still can see the issue.

**Comment by kavindya89** [comment]
@ian-ross will my suggested fix Ok or I need to try something else? I looked at many places where I can set this widget value. But couldn't find.

**Comment by ian-ross** [comment]
Seems reasonable.  The minimal change that makes things work is usually right.  Can you add something to the functional tests for this page to make sure we avoid regressions in the future?

**Comment by kavindya89** [comment]
@ian-ross sure will do it!

**Comment by kavindya89** [comment]
@ian-ross I thought bit deeper. it seems checking whether value is None can lead to security breach. For example, if some person edited form and didn't send any input for permissions like Administrator user, then every user will get administrator permission I'm going to change it to check Administrator role which will pass to widget.

**Comment by kavindya89** [comment]
@ian-ross Finally added this https://github.com/Cadasta/cadasta-platform/pull/726 as the fix. Please let me know anything need to be changed
