### ISSUE TITLE
Server error when uploading a questionnaire (after trying to do so with a incorrect one)

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#640]
### Steps to reproduce the error

I saw this in demo in this project: 
https://demo.cadasta.org/organizations/uttaran/projects/uttaran-vulnerable-landowner/

STR: 
1. I was uploading a new version of the questionnaire and didn't realize that there was an error in the syntax. 
2. Brian's parsing worked nicely and let me know the what the issue was (I think missing a label or something like that)
3. I fixed the error and try to upload the new version of the questionnaire
4. I get an server error from that moment on

One the other hand, this last correct version of the questionnaire worked well in a fresh project. 

I tried the workaround of accessing to /edit/details and reloading the questionnaire but didn't work. I also think it's not related with #605 as there were anything weird in the settings tab. 

I tried to replicate with other projects but I have not been able to. 
### Actual behavior

Server error shown 
### Expected behavior

Able to reload the questionnaire.

**Comment by bjohare** [comment]
This is a type of schema conflict of the kind discussed here https://github.com/Cadasta/django-jsonattrs/issues/4.

The offending attribute is `amount_othersland`.

The questionnaire was originally uploaded on 2016-09-03. The attribute type of `amount_othersland` was originally `text`. The questionnaire was uploaded twice more with `amount_othersland` as `text`. There was one successful submission during this time where the value of the attribute was a empty string.

Subsequent questionnaire uploads changed the `amounts_othersland` field to type `decimal` with either a default of `0.0` or `0`. All these uploads succeeded as there was nothing wrong with the form, however on redirection to the project dashboard the attempt to load spatial units fails with a _ValidationError_ in _jsonattrs_. The `amount_othersland` attribute type is now a decimal and `""` is not a decimal value.

It doesn't look like this case has been covered by recent changes to **django_jsonattrs**? @ian-ross  can you confirm?

**Comment by ian-ross** [comment]
I think that although this is more or less the same case as https://github.com/Cadasta/django-jsonattrs/issues/4, there's one difference that's screwing things up.  In the "normal" schema update case, you change a model instance field value that's used to select the attribute schema: change a selector field, the schema changes and `django-jsonattrs` checks for potential conflicts in attribute field types (either when you first save a model instance, or when you call the `schema_update_conflicts` function).

In the case here, you're creating a new schema and you're updating the `current_questionnaire` selector in the project to force selection of the new schema.  That *would* (sort of, possibly) work, except for the fact that you create the new schema *after* you update the `current_questionnaire` selector field and save the project instance (https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/questionnaires/managers.py#L172-L180).  That means that `django-jsonattrs` doesn't detect any incompatible schema changes until the next time you save a model instance.

In fact, things are worse than that, because you're doing something that `django-jsonattrs` doesn't support *at all*, which is using a non-primary key field from a foreign key-related model as a schema selector (`project.current_questionnaire` in the `JSONATTRS_SCHEMA_SELECTORS` in the settings file).  To explain why this is a problem, let's assume we're using the schema selector settings as they currently are, so for `SpatialUnit`, the selectors are `(project.organization.pk, project.pk, project.current_questionnaire)`.  Let's say that we have a `Project` `proj`, and a spatial unit `sp`, where `sp.project == proj`.  If you were to change the project that `sp` is in, `django-jsonattrs` would be able to detect any associated schema change, because when you save `sp`, `django-jsonattrs` gets a `pre_save` signal (set up here: https://github.com/Cadasta/django-jsonattrs/blob/master/jsonattrs/decorators.py#L29) and it can do the schema checks in that signal handler.  In contrast, if you update `project.current_questionnaire`, the `pre_save` signal on `sp` doesn't  fire (you're not updating `sp`, after all).

In order to handle all the possible cases here, whenever a model is decorated with the `fix_model_for_attributes` decorator, `django-jsonattrs` would need to install `pre_save` signal handlers on all the model classes that are used anywhere in the schema selectors (for the case here, that would mean both `Project` and `Organization`).  Then, any time that you update one of the selector fields (`project.current_questionnaire`, for example), `django-jsonattrs` would need to do the schema update checks.

Given the way that you're using the `current_questionnaire` field here, I'm guessing that this is something you'd like to work, right?  If `django-jsonattrs` was made to work this way and you created the schemas before updating `project.current_questionnaire` and saving the project instance, `django-jsonattrs` would give an exception in this case (trying to change a `text` field into a `decimal` field).

(There is a further extension of how this might work that would allow you to do some updates like this: if you wanted blank `text` fields to be converted to the new `default` value, so allowing updates from `text` to `decimal` in some cases, `django-jsonattrs` would need to find all the attributes associated with the "before" schema and update them to work with the "after" schema.  That's an extra and possibly slightly unwieldy step though, since it would require scanning a lot of attributes when schemas are updated.)

**Comment by bjohare** [comment]
@ian-ross thanks for the above, I hadn't realised the issue with using non-pk fields on foreign key related models as selectors, but it makes sense. We do need changes to these fields to be detected. At some point in the future we'll need to support multiple questionnaires so the use of `current_questionnaire` will be dropped but in all probability we'll still need to use non-pk fk fields (I haven't really thought much further about this though). The solution you're proposing (installing `pre_save` handlers and attempting value migration where possible) sounds reasonable. Allowing changes to schema selectors is very much like allowing the user to apply a database migration on a production system with out the kind of testing we would accept for our own migrations and I can see this whole are becoming much more complex as we allow multiple concurrent questionnaires and partial updates to questionnaires....

**Comment by ian-ross** [comment]
OK, I've opened an issue on django-jsonattrs to track this stuff: https://github.com/Cadasta/django-jsonattrs/issues/8

**Comment by dpalomino** [comment]
Moving this to low priority until we have a GUI solution for handling forms.

**Comment by dpalomino** [comment]
Low priority issue and no relevant with the project creation wizard feature being planned. Closing the issue.
