### ISSUE TITLE
Resource API Views

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#67]
Implement views and tests for:

- [ ]  Create
- [ ]  Update
- [ ]  List (with search, filter, sort)
- [ ]  Detail view
- [ ]  Summary view
- [ ]  Archive/unarchive
- [ ]  Assignment to Parcel, Relationship or Party

In each case, tests should include:

Successful requests;
Unauthenticated requests;
Unauthorized requests;
Invalid payloads.

We should limit initial files to a specific set of types. It should be configurable what types. 

(broken out from #15)

**Comment by wonderchook** [comment]
@nastynoel I'm thinking we should limit the file types initially for what can be uploaded. Here is what I'm thinking initially: mp3, pdf, png, jpg, mp4.

Thinking it should be something configurable by system rather than something that takes a code push to change.

**Comment by nastynoel** [comment]
@wonderchook some additional recommendations



.zip – particularly in lower bandwidth environments it may be easier for
users to upload a compressed data packet that contains multiple resources
within a single folder

.xlsx – I could see potential use cases where users might have captured
other data in tabular form that they don’t want/need stored in a DB
structure on the platform, e.g. Community mapping of village boundaries
where a resource file could be an excel list of households found within the
single boundary of the village.

.gif & .tif – open question as to whether these are needed now, including
GeoTIFF support?



*From:* Kate Chapman [mailto:notifications@github.com]
*Sent:* Wednesday, 17 February 2016 7:21 AM
*To:* Cadasta/cadasta-platform <cadasta-platform@noreply.github.com>
*Cc:* nastynoel <ntaylor@cadasta.org>
*Subject:* Re: [cadasta-platform] Resource API Views (#67)



@nastynoel <https://github.com/nastynoel> I'm thinking we should limit the
file types initially for what can be uploaded. Here is what I'm thinking
initially: mp3, pdf, png, jpg, mp4.

Thinking it should be something configurable by system rather than
something that takes a code push to change.

—
Reply to this email directly or view it on GitHub
<https://github.com/Cadasta/cadasta-platform/issues/67#issuecomment-184861460>
.

**Comment by oliverroick** [comment]
We should also consider implementing downsizing of images for use on the web, while keeping the original resolution for printable reports

**Comment by nastynoel** [comment]
Agreed. This is something that also came in discussions with Chandra when
looking at the wireframes.



*From:* Oliver Roick [mailto:notifications@github.com]
*Sent:* Wednesday, 17 February 2016 9:08 PM
*To:* Cadasta/cadasta-platform <cadasta-platform@noreply.github.com>
*Cc:* nastynoel <ntaylor@cadasta.org>
*Subject:* Re: [cadasta-platform] Resource API Views (#67)



We should also consider implementing downsizing of images for use on the
web, while keeping the original resolution for printable reports

—
Reply to this email directly or view it on GitHub
<https://github.com/Cadasta/cadasta-platform/issues/67#issuecomment-185132961>
.
