### ISSUE TITLE
Removing a resource from the project does not affect resource count on dashboard.

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#674]
### Steps to reproduce the error
Attach a resource to a project.
Check the resource count on the dashboard.
Delete the resource from the project.
Check the resource count on the dashboard again.

### Actual behavior
Project dashboard reflects total number of resources loaded, regardless of whether or not they're still loaded.

<img width="1280" alt="screen shot 2016-09-12 at 1 06 40 pm" src="https://cloud.githubusercontent.com/assets/8128188/18445249/b2a78ed0-78ea-11e6-9487-a80d85606752.png">
<img width="1280" alt="screen shot 2016-09-12 at 1 06 37 pm" src="https://cloud.githubusercontent.com/assets/8128188/18445250/b43e2efc-78ea-11e6-8a1d-60db79f90f2f.png">

### Expected behavior
Dashboard count reflects the number of resource currently loaded.

**Comment by wonderchook** [comment]
@linzjax I'm thinking this doesn't need to be fixed this week, but would be good to get into Sprint 9. Is this something you want to take a stab at?

**Comment by seav** [comment]
Oops. This is related to the work that I did for improving handling of resources. Deleted (archived) resources should not count towards the total. This is easily fixed by filtering the queryset with`exclude(archived=True)`.

One question I had for this was whether to show the *true* total to those who have the `resource.unarchive` permission. But I think it would be better and simpler to just show the filtered total to everyone.

**Comment by wonderchook** [comment]
@seav agreed on showing the filtered total to everyone

**Comment by divyabiyani** [comment]
@seav Could you please let me know the file related to this bug so that I can amend the code.
