### ISSUE TITLE
Refine user messaging and flow for anonymous users

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#677]
### Steps to reproduce the error
1. Open https://platform-staging-api.cadasta.org/organizations/nt-mapping/projects/geelong-bellarine/
2. Open the parcel via the map.
3. You're redirected to the login page, but feedback why you end up there is not given.
### Actual behavior

No feedback is given on the login page. 
### Expected behavior

If a user is redirected to another page because a login is required an appropriate message should be displayed informing the user that they need to login the view the location.
### Additional thoughts

I can see the location on the map, but I can't access it. This seems a bit confusing to me. If I don't have permission to view a parcel (as an unauthenticated user), why can I see its geometry on the map. There's either an issue with how the policies are setup or the views have the wrong permissions requirements.

**Comment by clash99** [comment]
Related to #575

**Comment by Edely** [comment]
Hello. Can I work in this issue? I am going to apply for Outreachy and I think this could be a good start. I already installed the Cadasta platform locally.

**Comment by oliverroick** [comment]
@Edely Yes, go ahead!

**Comment by Edely** [comment]
I added an alert if user was redirected.

**Comment by clash99** [comment]
@dpalomino When its ready, can you send me a link to the permissions document?  I'm going to try to build a strategy across the platform for messaging when login is required and user permissions are limited.

**Comment by clash99** [comment]
This might be a related permissions issue.

As the **project administrator**, I have a project with 1 project resource and 1 party resource.  This is what I see when I select the Resources tab in the subnav:
<img width="1119" alt="screenshot 2016-11-10 12 20 35" src="https://cloud.githubusercontent.com/assets/1119621/20188889/6346cf8e-a740-11e6-8d46-4e5089679898.png">

As a **public user (not logged in)**, I get redirected to the sign in page when I select the Resources tab in the subnav:
<img width="1119" alt="screenshot 2016-11-10 12 24 53" src="https://cloud.githubusercontent.com/assets/1119621/20188985/d78f52bc-a740-11e6-8156-40e377848c9a.png">

As a **logged in user that is not a member of the project**, this is what I see when I select the Resources tab in the subnav (although 2 resources are listed on the overview tab):
<img width="1119" alt="screenshot 2016-11-10 12 13 48" src="https://cloud.githubusercontent.com/assets/1119621/20189012/f5e87f54-a740-11e6-8369-8b32d9becc63.png">

If I can't view the resources because I don't have permissions I would expect to see a message or alert, not an empty table.

**Comment by clash99** [comment]
@bethschechter I think we should add some sort of additional help on these alerts such as "?" 

- Why can't I view this?  
- Why don't I have permission? 
- Can I request permission to view?

<img width="1118" alt="screenshot 2016-11-10 12 14 17" src="https://cloud.githubusercontent.com/assets/1119621/20189549/480ff9c2-a743-11e6-982d-378b6ebdfff5.png">

**Comment by clash99** [comment]
If non-project members (either public or registered users) can only see a project overview page, I would recommend changing the project view to something like this with the left project sidebar removed:  

<img width="1257" alt="screenshot 2016-11-11 10 47 22" src="https://cloud.githubusercontent.com/assets/1119621/20222849/896ef670-a7fc-11e6-8c2e-b1326a756b99.png">

@dpalomino: Does this make sense?  That way users aren't receiving lots of "NO!" messages.  I would also recommend using some sort of messaging in the right detail like this:  If you are a member of this project, sign-in to view project details.  If you are not a member of this project and would like to be, request permission.

**Comment by clash99** [comment]
For this task I recommend creating a new page that explains to the user why they were sent there and provides both an option to sign in or register for a new account.  We need to get the messaging right to set user expectations because unless they are a member of the project, they still won't get to see project details.  I think this action combined with removing the project sidebar (screenshot above), will make for a better and definitely less-confusing user interaction. 

![signin page for required permissions](https://cloud.githubusercontent.com/assets/1119621/20223944/8d9b0c84-a801-11e6-8378-20ab0d69af87.png)

Let me know what you think.

**Comment by wonderchook** [comment]
I like the cheesy 🧀 🐭. 

One thought about the account sign-up we should make sure that the user doesn't expect they are going to get to see everything. Just meaning I could see how it would be frustrating to sign-up and then still get access denied. Not sure how to balance this though, requires some thought.

**Comment by dpalomino** [comment]
Looks really nice @clash99. Regarding the account sign-up, maybe we can put some wording to explain to the user that they need also to have permission to see the details. 

What about something like (changes in bold): 

"Because we care protecting **your** sensitive data, you must sign in **to verify that you are granted to** view the project information. Please sign in to continue. "

**Comment by bethschechter** [comment]
@clash99 copy this! Added your note to a list of notes about the walkthrough. I also like the additional page you mocked up.

**Comment by clash99** [comment]
I've modified the login page so that if you are being redirected from within a project, you see this screen.  Thoughts on the text messaging here?  

<img width="1379" alt="screenshot 2016-11-14 16 56 27" src="https://cloud.githubusercontent.com/assets/1119621/20286238/5b87db28-aa8b-11e6-8217-823c2da3e9f6.png">

**Comment by oliverroick** [comment]
Maybe we should point out that it's likely users still won't have permission when they sign in/sign up — just to avoid confusion. The message reads like "sign up and everything will be ok"

**Comment by clash99** [comment]
Here is the proposed flow for a Public User for Projects and Organizations:

![2 0_ public user](https://cloud.githubusercontent.com/assets/1119621/20364522/0ebc3878-ac09-11e6-8516-e029c87e2ae3.png)

![3 0_ public user](https://cloud.githubusercontent.com/assets/1119621/20364566/40de67c2-ac09-11e6-8577-416fd1dfd534.png)

For the new messaging on the sign in page I have updated it to:

Because we care about protecting your sensitive data, you must sign in to verify you have the proper permission to view project information. Access to project data is restricted to current project members only. Please sign in to continue.

**Comment by clash99** [comment]
Here is the layout flow for Project and Organizations for the different user roles:  https://drive.google.com/a/cadasta.org/file/d/0BzpiEtMtHC3renRpeXVZLXNyQlE/view?usp=sharing

In summary here are my recommendations:
- Remove the inner subnav for non-project members for both projects and organizations
- Remove project overview stats for public users
- Add new sign in language on project overview for public users
- Add messaging to sign in page for public users
- Add option for registered users without project permissions to request project access (not sure if we are ready for this one)

Take a look and let me know what you think.  Thanks, Chandra

**Comment by clash99** [comment]
New sign in page for redirected users:
<img width="1336" alt="screenshot 2016-11-17 17 42 56" src="https://cloud.githubusercontent.com/assets/1119621/20412607/639987da-aced-11e6-8152-e13250d510a0.png">

**Comment by clash99** [comment]
**Anonymous User layout**

Organization Overview

<img width="1403" alt="screenshot 2016-11-18 10 25 24" src="https://cloud.githubusercontent.com/assets/1119621/20437393/6170338c-ad79-11e6-8e24-cf52f9bd7489.png">

Project Overview
<img width="1403" alt="screenshot 2016-11-18 10 26 58" src="https://cloud.githubusercontent.com/assets/1119621/20437440/91202362-ad79-11e6-95db-74ce35d7f25c.png">

**Comment by clash99** [comment]
**Registered User with no permissions**

Organization Overview (same as Anonymous User)

Project Overview (no sidebar nav)

<img width="1402" alt="screenshot 2016-11-18 10 31 09" src="https://cloud.githubusercontent.com/assets/1119621/20437582/261503ac-ad7a-11e6-9d01-3fe536231bb7.png">

**Comment by clash99** [comment]
**Registered User with project permissions** (views vary slightly based on granular permissions)

Organization Overview (unchanged)

<img width="1403" alt="screenshot 2016-11-18 10 32 53" src="https://cloud.githubusercontent.com/assets/1119621/20437681/7b5b5a50-ad7a-11e6-8616-6eb1dd442523.png">

Project Overview (unchanged)

<img width="1402" alt="screenshot 2016-11-18 10 32 40" src="https://cloud.githubusercontent.com/assets/1119621/20437690/84232c62-ad7a-11e6-9435-2bd3d36cc34e.png">
