### ISSUE TITLE
xform errors are still visible after re-upload of working xform

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#679]
### Steps to reproduce the error
1. Upload [this XLSForm](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/questionnaires/tests/files/test_standard_questionnaire_bad.xlsx) to a project and save the project.
2. You should see an error displayed with the form field.
3. Upload [this XLSForm](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/questionnaires/tests/files/test_standard_questionnaire.xlsx) to a project and save the project.
### Actual behavior

The errors of the previous upload are still visible.
### Expected behavior

The errors of the previous upload should be removed from the page when a valid XLSForm is uploaded.

**Comment by clash99** [comment]
Possibly related to #322

**Comment by wonderchook** [comment]
@clash99 since this is related to #322 does it make sense to manage it during this sprint?

**Comment by clash99** [comment]
Yep, I'll take it!

**Comment by dpalomino** [comment]
@clash99, any feedback on this? Thanks!

**Comment by clash99** [comment]
Added script so that when remove link is clicked, the error message below is hidden and the has-error class is removed from the form-group.

**Screenshot Step 1:**  (initial view)

![screenshot 2016-11-03 11 17 25](https://cloud.githubusercontent.com/assets/1119621/19974705/5d13bcfa-a1b7-11e6-9c16-40d2deef3067.png)

**Screenshot Step 2:** (attempting to upload bad file)

![screenshot 2016-11-03 11 17 37](https://cloud.githubusercontent.com/assets/1119621/19974722/6d19f06a-a1b7-11e6-8fdf-90f010adf63c.png)

**Screenshot Step 3:**  (after submit)

![screenshot 2016-11-03 11 17 16](https://cloud.githubusercontent.com/assets/1119621/19974752/8a55f2fa-a1b7-11e6-804a-e5754135bddb.png)

**Screenshot Step 4:**  (remove link brings back to initial view)

![screenshot 2016-11-03 11 17 25](https://cloud.githubusercontent.com/assets/1119621/19974777/9f48fb58-a1b7-11e6-9dc3-11bc54631e41.png)

I've added this to the two questionnaire file upload areas.  

@bjohare The file upload uses a bit of a different flow (no remove link) so I don't know if we want to change that around to match at this time but if these types of file errors start to show, we can implement something similar on that page too.
