### ISSUE TITLE
Resources should accept or convert audio files besides mp3

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#683]
### Steps to reproduce the error

I filled out a questionnaire on ODK that had the option to record audio. When I recorded it using my android tablet, it saved as an `.amr`. Kate's android phone saved it as an `.m4a` file. We either need to expand the options for audio resources, or automatically convert them to `.mp3` when they're submitted.
### Actual behavior

Sad, failed `400` error message.
### Expected behavior

Exciting new audio submitted as a resource.

**Comment by wonderchook** [comment]
@dpalomino is this needed for a current partner? (trying to figure out when to schedule it)

**Comment by dpalomino** [comment]
Yes, there are some partners using this, and as you were mentioning different Android devices are using different default audio formats. Mine is generating .amr as well.

I think we would need to address this as soon as we can, because in practice this prevents to collect audio information in the forms. Can we move this at least to Sprint 9?

**Comment by ian-ross** [comment]
There are two parts to this.  The first part is accepting weird audio formats as uploads for resources.  This shouldn't be difficult to do, since it's just a matter of adding the relevant MIME types to the list we accept.  The second part is converting these formats to some common format that people will understand when they download.  For example, AMR is a standard format for voice recording, but I don't think all media players understand it, so we might want to transcode it to MP3 and offer that as a fallback format for clients that don't understand AMR.  This is a more difficult job, and definitely not one that will happen in Sprint 9, because it involves having some sort of background task management to run the file conversions without locking up the main Django web app.  That's doable, and it could be done reusing some of the task management code I'm writing for Field Papers, but it's a much bigger job than just accepting the relevant file formats for upload.

**Comment by dpalomino** [comment]
Thanks a lot @ian-ross for the analysis! The second option would be a great solution. However maybe we could more easily just add the mime types so data collectors could submit the audio files, no matter which codec is being used in their device. They can always use an external audio converter when downloading these audio files. And I suspect that there would be a lot of different formats used by different devices, so implement the transcodification for all of them could be hard...  

What do you think?

**Comment by ian-ross** [comment]
For the moment, just adding the MIME types is probably the thing to do.  The actual transcoding would be easy (ffmpeg or mplayer or one of those tools can be set up with codecs for more or less everything), but the management of the background tasks is difficult -- if someone uploads a couple of hours of audio, you don't want the Django server sitting there transcoding all of that and not serving any other requests.  So you need some sort of task queue to deal with transcoding in the background, either using a simple queuing system like Celery to do the transcoding on the same machine as the Django server or (better) farming those tasks out to something like AWS Lambda.  That all requires quite a bit of machinery and isn't simple.

**Comment by dpalomino** [comment]
Thanks Ian. I think transconding would not be a priority, so we could very safely go just with the addition of the mime types. *If* it is something really simple, do you think it'd be possible to fix this for our Monday release? We're not offering audio resources to partners now because of this (as we cannot control which devices will be using). It is not super critical, but if there is no risk it would be nice to have...

**Comment by ian-ross** [comment]
Well, in order to do it, we need to know what audio formats you want to use and what MIME types they appear as from the users' devices.

**Comment by seav** [comment]
We could just ingest all `audio/*` types listed here minus the `audio/vnd.*` types, or maybe even further restricted to the ones that have an RFC: http://www.iana.org/assignments/media-types/media-types.xhtml#audio

**Comment by ian-ross** [comment]
That's not a bad idea.  I wonder about how accurate the reporting of MIME types is from mobile devices: when Kate uploads a .m4a file from her phone, does it get detected as audio/mp4, for instance?  I really know nothing about this stuff, but it doesn't seem very well supported (e.g. the sort of thing reported in https://github.com/Cadasta/cadasta-platform/issues/692).

**Comment by wonderchook** [comment]
Okay so let's add the mime types for sprint 9 and worry about all the processing stuff for later. @ian-ross I think this background processing that you suggested is a core piece of infrastructure we'll want at some point, but you are right it is more complicated and not a quick fix.

**Comment by wonderchook** [comment]
@dpalomino can you figure out which mime types we need to add?

**Comment by dpalomino** [comment]
@wonderchook, I think I agree with @seav, Android is quite not standard with this things and the variability among Android versions and vendors that make their own customized builds is important. At least probably we should support the ones contained in this table: 

https://developer.android.com/guide/appendix/media-formats.html

The mimetype list is, if I'm not wrong: 

audio/aac
audio/aacp
audio/amr,
audio/3gpp,
audio/3gpp2
audio/x-flac (I think this is uncommon)
audio/mpeg1
audio/MPA2
audio/mpa-robust3
audio/midi
audio/x-midi
audio/ogg
audio/opus
audio/vnd.wave (rare?)
audio/wav
audio/wave
audio/x-wav

But I think there could be some specific devices with supporting others as well. Probably the esiest thing to do is just add audio/* as Eugene said. Also because we cannot assure that some weird customized Android devices were using different ones. 

@seav, why you were suggesting to skip audio/vnd.* (just curiosity). I saw this as a supported format in Android (although probably very uncommon).

**Comment by wonderchook** [comment]
One concern I have with adding audio/* is with "what" people might upload. @amplifi does this concern you from a security perspective?

**Comment by seav** [comment]
@dpalomino, "vnd" is for vendor-specific types. I figured that if we would add a lot of MIME types, it would be best to stick to standardized formats at first and then just add sppecific types as needed.

**Comment by amplifi** [comment]
@wonderchook, audio mimetypes should be safe to whitelist. Unrelated to that particular group of types, I think it would be good to do a security audit of our file upload process and handling. I'll make a specific task for that.

**Comment by wonderchook** [comment]
closing since it appears to be finished!
