### ISSUE TITLE
Can sign-in and use the platform without email-id verification.

### ISSUE THREAD

**Issue by agentsimran** [Cadasta/cadasta-platform#695]
### Steps to reproduce the error

1. Create an account with a valid email-id.
2. Access the dashboard even without clicking on the mailt verification link.
3. Log-out.
4. Log back in. Again access all the functionalities of the platform without verifying.

### Actual behavior

Access the Cadasta-platform even without verifying the email-address provided in the registration form.

### Expected behavior

The registration form should lead to a link which stops access to the platform unless mail-id is verified.
Again, logging in should display a comment that says "email not verified"

**Comment by ian-ross** [comment]
This is the expected behaviour.  You get a 48-hour grace period before you're required to validate your email.  Try leaving the login without validating the email for a few days then try logging in.  You should get a message saying that your email needs to be validated.

I'm going to close this now, but feel free to reopen it if you check after the grace period and you can still log in without validating your email.
