### ISSUE TITLE
Update "e-mail" to "email" in text on pages and email text

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#709]
Based on form updating project, noticed different uses of "e-mail" and "email".  This issue is to update to standardized "email" and track page inventory.

**Comment by clash99** [comment]
Didn't make any changes to translated text.

**Comment by ian-ross** [comment]
Do you mean that you didn't update any of the translations, or you didn't update any text that gets translated (i.e. strings within `_(...)` in Python code or `{% trans ... %}` in templates)?  If it's the former, that's the right thing to do: some languages have settled on one or the other of "email" or "e-mail" as the standard, so there isn't the same wiggle room as in English.  For instance, as far as I can tell, Portuguese uses "e-mail" more or less exclusively (http://www.wordreference.com/enpt/email).  German also seems to prefer "E-mail" over "Email" (because "Email" is the German word for enamel).  And French is weird, because everyone says "email" or "e-mail" informally, but the "real" word is "mél"...

**Comment by ian-ross** [comment]
Never mind, I see your PR.  Let me take a look there...

**Comment by clash99** [comment]
@ian-ross - I only touched the English versions since the purpose is to standardize what Cadasta uses in its English communication.

**Comment by clash99** [comment]
Updating Transifex source language will take care of most of these changes.  I will include other small changes in my form branch.

**Comment by clash99** [comment]
I'm suggesting pushing this off to next sprint since its a low priority.

**Comment by clash99** [comment]
- [ ] email_confirmation_message.txt
- [ ] email_confirmation_subject.txt
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by clash99** [comment]
- [ ]
