### ISSUE TITLE
Server error when adding a new member in the org that has more than one page list of projecs

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#782]
### Steps to reproduce the error

1. Go to an org with more than 10 projects
2. Try to add a new member
3. Be sure that the list of projects within the org has more than one page
4. Click on Save to assign member permissions

See details here: 
http://screencast.com/t/hOXlRmu6wUMP

### Actual behavior

Server error if there is more than one page of projects. If we choose to see 50/100 projects per page (so there is one page only) we had no error. 

### Expected behavior

No server error.

**Comment by seav** [comment]
I think this is similar to #507.

**Comment by seav** [comment]
As I suspect, the cause of this bug is the same as with #507. This bug is caused by the DataTables behavior. When DataTables manipulates the table pages, it actually removes the rows from the DOM. This means that when the form is submitted, only the visible rows get sent to the server and the server is throwing an `IntegrityError` error because the project roles of the project on other pages were not sent.
