### ISSUE TITLE
Archived project detail page is still accessible

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#783]
### Steps to reproduce the error

- Create a new project
- Archive the project
- You end up on the project detail page; the project is flagged as archived
- Go to the organization's project list; the project is not visible there

### Actual behavior

Not sure if it's really a bug but there are some inconsistencies. As a project manager I can still access the project detail page but it's not visible in the project list. Also I can't access any of the edit pages (edit permissions, details, etc); I get _Permission Denied_ there. 

### Expected behavior

Not sure, it should be consistent. If I'm can access an archived project, which makes sense a project manager, then it should be in the list of projects. And I should be able to access the edit pages; for instance, to unarchive the project

**Comment by linzjax** [comment]
Precursor: I made a lot of this permission stuff up as I went along, so any decisions made I can easily be convinced otherwise.

You can still access archived projects by filtering the `active/archived/all` select button next to the search box on a project list (if you don't see this, it's either because my most recent changes haven't been pushed to staging, or something's wrong).

I thought that org admin should still be able to view archived orgs/projs because they should be able to unarchive them, but do _nothing_ else. But if you archive a project, should you be redirected to a project list? Is it too hard to find it again if you do this on accident?

You can still unarchive the project, even if you can't select project edit.

**Comment by linzjax** [comment]
(this fix has already been pulled into master, but) If you select view 100 projects at the bottom of the table so that the project list displayed is longer, the select button might appear if it's missing.

**Comment by oliverroick** [comment]
Ah I see, I hadn't seen the filter dropdown. This all makes sense now. But then we should hide the edit page links on archived projects. Closing this and opening a new issue.
