### ISSUE TITLE
Improve Performance django-jsonattrs

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#824]
Tasks need to be outlined at the beginning of the sprint.

**Comment by dpalomino** [comment]
A couple of examples where this issue is causing a low performance (thanks to @amplifi for checking the logs!). 

In platform:

- Lagos project: either loading the overview page or accessing to a specific location. 

Overview (around 4 seconds to load): 
https://platform.cadasta.org/organizations/jei/projects/lagos-tenure-assessment-1/
One location (around 8 seconds to load one location): 
https://platform.cadasta.org/organizations/jei/projects/lagos-tenure-assessment-1/records/locations/ccykz2hmrn26a3s9vd4gnjkc/

- Telangana: 

Overview (around 5 secs to load):  
https://platform.cadasta.org/organizations/landesa/projects/telangana-survey/

One location (around 9 secs to load): 
https://platform.cadasta.org/organizations/landesa/projects/telangana-survey/records/locations/ay64rs2an99qua9xbz94xbc8/

In staging behaviour is similar.

**Comment by ian-ross** [comment]
@oliverroick What do you think about closing this for now?

**Comment by oliverroick** [comment]
Yes, closing this for the time being. We should address front-end performance next
