### ISSUE TITLE
Reset button ideally should not be present in the Edit Profile screen

### ISSUE THREAD

**Issue by aakanshavatsa** [Cadasta/cadasta-platform#844]
### Steps to reproduce the error

1. Sign in
2. Click on Edit Profile
3. Both "Change Password" and "Reset Password" options are present.

UI issue and found in the staging environment.

### Actual behavior
Ideally the Edit Profile section(taking inputs from different websites) should only have the Change Password option. Reset Password should be present when clicking "Forgot Password".
It is a redundant behavior to have both the options in the Edit Profile section.
<img width="1440" alt="reset issue" src="https://cloud.githubusercontent.com/assets/9761817/19431177/fc8f028a-9474-11e6-87c3-4b9fe9502576.png">

### Expected behavior

The Edit Profile section should only have the "Change password" option in line with other websites.

**Comment by seav** [comment]
I don't think this is redundant, and it is harmless to offer both options since they serve different purposes. The change password option expects that the user knows his/her password and wants to change it. while the reset password option assumes that the user has forgotten his/her password (since logging in) and wants to reset it now, instead of trying to log in the next time and then clicking the forgot password link.

**Comment by aakanshavatsa** [comment]
Thank you so much @seav for your thoughts.

I had one doubt - Isn't it highly improbable that a person who has logged in needs to reset his password? I have seen quite a few websites, and they do not offer "Reset Password" once you login.
