### ISSUE TITLE
Error unzipping download data file 

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#885]
### Steps to reproduce the error

- Go to this project: https://platform.cadasta.org/organizations/david-org/projects/david-testing/
- Download all data
- A zip file is obtained (attached for reference)
- Try to unzip the file

[david-testing.zip](https://github.com/Cadasta/cadasta-platform/files/562237/david-testing.zip)

### Actual behavior

At least when executed with Archive mac utility, the following error appears: "Unable to expand "david-testing.zip" into "directory". (Error 21 - Is a directory). 

The project only has a few records and one jpg resource, nothing very special. With others projects seemed to be working fine (I've tested with some and was ok). Not sure why this is failing in this project (or if would be also failing in a windows machine). 

Just opening the issue for further investigation (not sure how easy to reproduce this is). 

OS version: 10.11.06

### Expected behavior

zip file properly unzipped.

**Comment by ian-ross** [comment]
The ZIP file here is fine.  If there's some particular format the ZIP file needs to be in for the Mac Archive utility to work with it, you should specify what that is, but as far as `unzip` is concerned, it's a perfectly valid ZIP file and I can unpack it without problems.  The only problem it has is the naming of the resource files (they end up being called "`_`" instead of the correct filename).  That's being dealt with seperately: #884.
