### ISSUE TITLE
Research front-end performance improvement

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#893]
There are different approaches we can use to improve performance of our client-side components, most notably the map. We need to come up with an overview of options and and initial assessment of their suitability for our requirements.

A few directions we can look into:

- Improve performance of Leaflet.Deflate
- Server-side clustering
- Server-side rendering; serving maps through a tile map service
- Asynchronous loading of features; slicing up data either by geographic area or by pagination
- Vector tiles (putting this down for reference, I'm assuming vector tiles are not a feasible solution because we need to support our partners older machines.

**Comment by seav** [comment]
Technically, you can render vector tiles using any client-side technology: WebGL, HTML5 Canvas, or SVG, or even CSS-based shapes if somebody is crazy enough. Mapbox renders them using WebGL, while the [Leaflet.MapboxVectorTile plugin](https://github.com/SpatialServer/Leaflet.MapboxVectorTile) uses HTML5 Canvas.

If we are worried about supporting older computers, then it seems that our minimum requirements is actually a browser that renders Canvas/SVG because Leaflet uses Canvas/SVG to overlay the polygons and polylines. So we could use Leaflet.MapboxVectorTile if ever we choose to use vector tiles. This actually seems like a more lightweight solution compared to implementing our own TMS.

**Comment by seav** [comment]
Aside from the map, we also need to look into the DataTables. Our current implementation loads *all* the data. For most of our DataTables (like the list of tenure relationships for a location), I don't think this will be an issue because I don't expect the table to contain a huge amount of data (I doubt there will be thousands of relationships recorded for a location). But the rest of our DataTables, specifically the resources table in the Resources tab and the resources table when we want to attach an existing resource to a record, will load all project resource info. (There's also the page containing the list of all project parties but it is currently unreachable; see #768.)

**Comment by ian-ross** [comment]
The datatables shouldn't be too hard to deal with.  The library we're using for them supports all sorts of data sources, so we can use Ajax requests to API endpoints to get the data, as described in https://datatables.net/examples/data_sources/server_side.html.  (We should probably be providing a pagination interface for the API endpoints anyway.)

**Comment by oliverroick** [comment]
Below are the results of my research, which discusses possible next steps to improve client-side performance along with an initial high-level task breakdown. If there's anything I have missed or if the discussion is unclear please add to the comments below.

## Improving map performance

We currently have several views that include a map view or load the map in the background if they contain modals. Each time one of these views in accessed, the map and all of the project's features is loaded, which affects both front-end and back-end performance. When a user is navigating around a project, this approach piles up many redundant requests to the server. Instead of loading the map every time, we should load the map and all of the project's features once and cache the results. 

This means that part of the records area need to be redeveloped. Building on pour current layout with the map and the panel on the right-hand side, the idea is to only update the panel using asynchronous HTTP requests and never move or reload the map. 

Usually, we would use a JSON API to get and update models; parse the responses on client-side and update the UI accordingly. However, I would suggest to borrow from the concept of [Server-generated JavaScript Responses](https://signalvnoise.com/posts/3697-server-generated-javascript-responses) and render HTML snippets on the server and load them into the page on client-side. That way:

- We don't have to implement client-side logic to parse JSON responses and update the UI. This usually involves large frameworks and template-rendering engines. 
- We can re-use existing views and templates, which are already well-tested.
- We only have to maintain mostly server-side logic, which is easier to test.

To load the map initially we can switch JSON vector tiles, which are quite straightforward to implement on server-side, and use a Leaflet plugin on client-side (e.g. [TileLayer.GeoJSON](https://github.com/glenrobertson/leaflet-tilelayer-geojson/)).

### Possible task breakdown

- Update the views and templates listed below so they can be served asynchronously. For consistency, both the URLs and view classes should be moved to the `async` component the corresponding Django app. Scaffolding should be removed from the HTML template so only the contents of the right-hand side panel are rendered. 
- Implement minimal routing, so the URL displayed in the address bar is in sync with the current view. The view should be updated according to the URL when users access the page via a permalink. (Possibly of help: [A JavaScript router in 20 lines](http://joakim.beng.se/blog/posts/a-javascript-router-in-20-lines.html))
- Implement async loading into the client-side. This will involve designing and implementing a framework to handle information flows uni directional. Changes to the UI should only happen, when the URL in the browser changes. This should trigger and event, which will load the resource from the backend and display some loading info to the user. Upon receiving the response the loading info is removed and the contents are displayed in the panel. Ideally, we would track to app's current state in one central variable and update only the state when the user interacts with the platform. We would listen for changes to the stated and update the UI according to the current state. 
- Store the map position either in the browser session and/or the URL so it can be recovered through a permalink.
- Change `spatial.asyc.SpatialUnitList` so it can serve GeoJSON vector tiles. The view should support the [XYZ tile convention](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames).
- Change loading of features on the client-side to support GeoJSON vector tiles. 

### Affected views

- `organization.views.default.ProjectDashboard`
- `spatial.views.default.LocationsList`
- `spatial.views.default.LocationAdd`
- `spatial.views.default.LocationDetail`
- `spatial.views.default.LocationEdit`
- `spatial.views.default.LocationDelete`
- `spatial.views.default.LocationResourceAdd`
- `spatial.views.default.LocationResourceNew`
- `spatial.views.default.TenureRelationshipAdd`
- `party.views.default.PartyRelationshipDetail`
- `party.views.default.PartyRelationshipEdit`
- `party.views.default.PartyRelationshipDelete`
- `party.views.default.PartyRelationshipResourceNew`
- `party.views.default.PartyRelationshipResourceAdd`

## Improving page load

### Move processing of data tables to server

As [Ian points out](https://github.com/Cadasta/cadasta-platform/issues/893#issuecomment-258083597), we can move much of the functionality (sorting, pagination, filtering) for data tables to the server side. This will include implementing corresponding server-side views and changing front-end functionality accordingly. As [Eugene suggested](https://github.com/Cadasta/cadasta-platform/issues/893#issuecomment-258082969), we need to think about whether we want to apply this approach to all of our table views or just the ones the we expect to large amounts of data. 

#### Possible task breakdown

- Analyse which views we want to change to use server-side rendering.
- For each of these views implement a view that server data as JSON asynchronously. Each of the async views should support pagination including varying page lengths, sorting, search as well as any combination of those.
- Change all of the original views so data is loading asynchronously. 

### Minify and merge JavaScript files

Many of the libraries we use are split across different files and are not minified. We should merge files that are always used together and minify them. Files that can possibly be merged:

- Datatables: `datatables.min.js`, `dataTables.conditionalPaging.js`, `dataTables.selectFiltering.js`
- Parsley: `parsleyConfig.js`, `parsley.js`
- jQuery: `jQuery.min.js`, `bootstrap.min.js`
- Leaflet: There are several JS files loaded for all the map views, some if which are served from django-leaflet. We at least try to merge and minify the file which are not served from django-leaflet until we replace django-leaflet.

#### Possible task breakdown

- Research and implement an approach to merge and minify JS files that can be run during deployment. Files should also be merged and minified whenever they are changed in the dev environment. 

### Static files loading

We currently load static files (CSS, Layout images, JavaScript) from either our own EC2 instance or a CDN. Some of the CDNs sometimes have slow loading times or become unresponsive.

I would suggest to centralise loading of static files. We can use an S3 bucket to serve those files. We need to consider though that our instances may require different versions of libraries, so we either need to think about versioning or running separate S3 buckets for all of our instances. 

#### Possible task breakdown

- Decide whether we want to continue using CDNs to serve static files. 
- Research and implement solution to serve different library versions to different environments. 
- Research and implement a way to host static files from S3, static files should be copied to S3 during deployment. In the dev environment, the same files should be hosted locally.

**Comment by wonderchook** [comment]
Solid research @oliverroick makes sense to me. 

Regarding the static files, it would seem to me we might want to have separate S3 buckets for instances. Just seems neater to me is my only reasoning though.

**Comment by amplifi** [comment]
I agree with @wonderchook on a separate bucket per env; it'll maintain our security isolation, simplify deployment/versioning, and enable us to purge per env as needed. Serving from S3 is just a matter of enabling that feature and updating our links to the new URLs, then I can update the deployment process to collect static files in S3 rather than local. As a heads up, S3 should be fine performance-wise for a year or so, then we'll want to return to using a (better) CDN (like Fastly) unless there are improvements to S3. I'm on board with switching to S3 now.

Moving to server-side generation is a solid plan. We can run load testing when it's ready for staging to determine whether we need to scale up our EC2 instances to support the added compute.

**Comment by seav** [comment]
A general comment for the map performance section is that this seems to be going back towards the one-page app structure that we were originally aiming for before we went with implementing Django views. Given that most of the records pages show a map anyway, it might make sense to tackle this one-page app task as a cohesive whole instead of just targeting the pages that have a map.
